INSERT INTO `Modules` (`Id`, `Deleted`, `IsSystem`, `ModuleName`, `ModuleControler`, `ModuleView`) VALUES
(6, 0, 0,  '<!--{$word143}-->', 'UsersItem', 'MyProfile'),
(7, 0, 0, '<!--{$word136}-->', 'WebEdit', 'Tree'),
(8, 0, 0,  '<!--{$word137}-->', 'WebEdit', 'TemplateEditor'),
(9, 0, 0, '<!--{$word139}-->', 'UsersItem', 'UserList'),
(10, 0, 0, '<!--{$word141}-->', 'UsersItem', 'UserGroup'),
(11, 0, 0, '<!--{$word100}-->', 'FilerepositoryManger', 'FileManager'),
(12, 0, 0, '<!--{$word95}-->', 'Settings', 'WebList'),
(13, 0, 0, '<!--{$word96}-->', 'Settings', 'LangList'),
(14, 0, 0, '<!--{$word97}-->', 'Settings', 'AdminLangs'),
(15, 0, 0, '<!--{$word98}-->', 'Settings', 'Words'),
(16, 0, 0, '<!--{$word131}-->', 'Settings', 'Modules'),
(17, 0, 0, '<!--{$word99}-->', 'Admin', 'Logout'),
(18, 0, 0, '<!--{$word163}-->', 'Admin', 'SelectLang'),
(19, 0, 0, '<!--{$word184}-->', 'Settings', 'UserDomain'),
(20, 0, 0, '<!--{$word195}-->', 'Settings', 'UserDomainDetail'),
(21, 0, 0, '<!--{$word231}-->', 'Settings', 'UserDomainValueList'),
(22, 0, 0, '<!--{$word235}-->', 'WebEdit', 'Detail'),
(23, 0, 0, '<!--{$word268}-->', 'WebEdit', 'TemplateDetail'),
(24, 0, 0, '<!--{$word270}-->', 'Components', 'HtmlEditor'),
(25, 0, 0, '<!--{$word287}-->', 'WebEdit', 'CssList'),
(26, 0, 0, '<!--{$word288}-->', 'WebList', 'CssEditor'),
(27, 0, 0, '<!--{$word288}-->', 'WebEdit', 'CssEditor'),
(28, 0, 0, 'Správce souborů - složky', 'WebEdit', 'FileFolder'),
(29, 0, 0, 'Správce soubor - fileupload', 'WebEdit', 'FileUploader'),
(30, 0, 0, 'Diskuze', 'WebEdit', 'Discusion'),
(31, 0, 0, 'Javascripty', 'WebEdit', 'JsList'),
(32, 0, 0, 'Detail javasriptu', 'WebEdit', 'JsEditor'),
(33, 0, 0, 'Formuláře', 'WebEdit', 'FormsList'),
(34, 0, 0, 'Editace formuláře', 'WebEdit', 'FormEditor'),
(35, 0, 0, 'Předefinované emaily', 'WebEdit', 'MailList'),
(36, 0, 0, 'Editace emailu', 'WebEdit', 'MailEditor'),
(37, 0, 0, 'Odeslané emaily', 'WebEdit', 'SendMailList'),
(38, 0, 0,  'Nástroje pro vývojáře', 'Settings', 'DeveloperTools');
