INSERT INTO `UserDomains` (`Id`, `Deleted`, `IsSystem`, `DomainName`, `DomainIdentificator`, `Template`, `Domain`, `EditValue`, `ShowNameInSubDomain`, `SaveHiddenColumn`) VALUES
(1, 0, 0, '<!--{$word728}-->', 'UserProfile', NULL, NULL, 0, '', ''),
(3, 1, 0, '<!--{$word729}-->', 'Folder', NULL, NULL, 0, '', ''),
(4, 0, 0, '<!--{$word730}-->', 'Article', NULL, NULL, 0, '', ''),
(6, 0, 0, '<!--{$word731}-->', 'FileUpload', NULL, NULL, 0, '', ''),
(7, 0, 1, '<!--{$word732}-->', 'BadWords', NULL, NULL, 1, '', ''),
(8, 1, 0, '<!--{$word733}-->', 'news', NULL, NULL, 0, '', ''),
(9, 0, 0, '<!--{$word734}-->', 'Logo', NULL, NULL, 0, '', ''),
(10, 0, 1, 'Článek na homepge', 'homepageArticle', 0, 0, 0, '', ''),
(11, 0, 0, 'Kontaktní formulář', 'ContactForm', 0, 0, 0, '', ''),
(12, 1, 0, 'Vyhledávání', 'Search', NULL, NULL, 1, '', ''),
(13, 0, 0, 'Výsledky vyhledávání', 'SearchResult', NULL, NULL, 0, '', ''),
(14, 1, 0, 'Registrace', 'register', NULL, NULL, 0, '', ''),
(15, 1, 0, 'Přihlášení', 'UserLogin', NULL, NULL, 0, '', ''),
(16, 0, 0, 'Langselect', 'Langselect', NULL, NULL, 0, '', ''),
(17, 0, 1, 'Mailingové skupiny', 'Mailinggroups', NULL, NULL, 1, '', ''),
(18, 0, 1, 'Měny', 'CurrencyList', NULL, NULL, 1, '', ''),
(19, 0, 0, 'Produkty', 'products', NULL, NULL, 0, '', ''),
(20, 0, 1, 'Přesměrování', 'Redirects', NULL, NULL, 1, '', ''),
(21, 0, 0, 'Košík', 'ShopCart', NULL, NULL, 0, '{TransportName} - {TransportPrice}', ''),
(22, 0, NULL, 'Doprava', 'ShopTransport', NULL, NULL, 1, '{TransportName} - <% FormatPrice(\'{TransportPrice}\',\'cs_CZ\',\'%.2n\')%>', ''),
(23, 0, NULL, 'Platba', 'Payment', NULL, NULL, 1, '{PaymentName} - <% FormatPrice(\'{PaymentPrice}\',\'cs_CZ\',\'%.2n\')%>', ''),
(24, 0, 0, 'Přihlášení uživatele', 'UserLoginComponent', NULL, NULL, 0, '', ''),
(25, 0, 0, 'Přihlášený uživatel', 'UserIsLogin', NULL, NULL, 0, '', ''),
(26, 0, 0, 'Odkaz', 'Links', NULL, NULL, 0, '', ''),
(27, 0, 1, 'Copyright', 'Copyright', NULL, NULL, 0, '', ''),
(28, 0, NULL, 'Slider', 'Slider', NULL, NULL, 0, '', ''),
(29, 0, NULL, 'Patička', 'Footer', NULL, NULL, 0, '', ''),
(30, 0, NULL, 'Výrobci', 'Manufacturer', NULL, NULL, 1, '{ManufacturerName}', ''),
(31, 0, NULL, 'Dotaz k produktu', 'ProductQuestion', NULL, NULL, 0, '', ''),
(32, 0, NULL, 'Nastavení eshopu', 'shopsettings', NULL, NULL, 1, '', ''),
(33, 1, NULL, 'Správa cronů', 'cronManager', NULL, NULL, 1, '', ''),
(34, 0, NULL, 'Heureka kategorie', 'HeurekaCategory', NULL, NULL, 1, '{CATEGORY_NAME}  - ({CATEGORY_FULLNAME})', 'CATEGORY_FULLNAME'),
(35, 0, NULL, 'Stavy objednávek', 'OrderStatus', NULL, NULL, 1, '', '');