INSERT INTO `WordGroups` (`Id`, `Deleted`, `IsSystem`, `GroupName`, `WordCS`, `WordEN`, `WordSK`, `WordDE`, `WordRU`, `WordRU,8`) VALUES
(1, 0, NULL, 'word1', 'Uživatelské jméno', 'Username', '', '', NULL, NULL),
(2, 0, NULL, 'word2', 'Heslo', 'Password', '', '', NULL, NULL),
(3, 0, NULL, 'word3', 'Vyberte web', 'Select the web', '', '', NULL, NULL),
(4, 0, NULL, 'word4', 'Vyberte jazyk', 'Select your language', '', '', NULL, NULL),
(5, 0, NULL, 'word5', 'Přihlášení do systému', 'Login to the system', '', '', NULL, NULL),
(6, 0, NULL, 'word6', 'Přihlásit se', 'Login', '', '', NULL, NULL),
(7, 0, NULL, 'word7', 'Není nainstalován žádný web. Instalaci webu můžete provést', 'There is not installed web. You can install', '', '', NULL, NULL),
(8, 0, NULL, 'word8', 'Vyberte web', 'Select the web', '', '', NULL, NULL),
(9, 0, NULL, 'word9', 'Vyberte ...', 'Select...', '', '', NULL, NULL),
(10, 0, NULL, 'word10', 'Vyberte jazyk', 'Select your language', '', '', NULL, NULL),
(11, 0, NULL, 'word11', 'Není nainstalován žádný jazyk!', 'There is no installed language!', '', NULL, NULL, NULL),
(12, 0, NULL, 'word12', 'Zadali jste špatné přihlašovací údaje.', 'You have entered the wrong credentials.', '', NULL, NULL, NULL),
(13, 0, NULL, 'word13', 'Přidat jazyk administrace', 'Add the language of administration', '', NULL, NULL, NULL),
(14, 0, NULL, 'word14', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(15, 0, NULL, 'word15', 'Jméno jazyka', 'Name language', '', NULL, NULL, NULL),
(16, 0, NULL, 'word16', 'Identifikátor jazyka', 'Language identifier', '', NULL, NULL, NULL),
(17, 0, NULL, 'word17', 'Nastavení jazyků', 'Setting the language', '', NULL, NULL, NULL),
(18, 0, NULL, 'word18', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(19, 0, NULL, 'word19', 'Oprávnění editace', 'Permissions editing', '', NULL, NULL, NULL),
(20, 0, NULL, 'word20', 'Jméno jazyka:', 'Name language:', '', NULL, NULL, NULL),
(21, 0, NULL, 'word21', 'ROOT URL:', 'ROOT URL:', '', NULL, NULL, NULL),
(22, 0, NULL, 'word22', 'Přidat web', 'Add website', '', NULL, NULL, NULL),
(23, 0, NULL, 'word23', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(24, 0, NULL, 'word24', 'Oprávnění editace', 'Permissions editing', '', NULL, NULL, NULL),
(25, 0, NULL, 'word25', 'Jméno webu', 'The site name', '', NULL, NULL, NULL),
(26, 0, NULL, 'word26', 'Editace slov administrace', 'Editing words administration', '', NULL, NULL, NULL),
(27, 0, NULL, 'word27', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(28, 0, NULL, 'word28', 'Jméno skupiny slov', 'Name of words group', '', NULL, NULL, NULL),
(29, 0, NULL, 'word29', 'Exportovat data', 'Export data', '', NULL, NULL, NULL),
(30, 0, NULL, 'word30', 'Nastavení exportu', 'Export settings', '', NULL, NULL, NULL),
(31, 0, NULL, 'word31', 'XML', 'XML', '', NULL, NULL, NULL),
(32, 0, NULL, 'word32', 'XLS', 'XML', '', NULL, NULL, NULL),
(33, 0, NULL, 'word33', 'Historie objektu', 'History item', '', NULL, NULL, NULL),
(34, 0, NULL, 'word34', 'Akce', 'Action', '', NULL, NULL, NULL),
(35, 0, NULL, 'word35', 'Uživatel', 'User', '', NULL, NULL, NULL),
(36, 0, NULL, 'word36', 'IP adresa', 'IP adrresses', '', NULL, NULL, NULL),
(37, 0, NULL, 'word37', 'Datum změny', 'Date of change', '', NULL, NULL, NULL),
(38, 0, NULL, 'word38', 'Data', 'Data', '', NULL, NULL, NULL),
(39, 0, NULL, 'word39', 'Obnovit verzi', 'Restore version', '', NULL, NULL, NULL),
(40, 0, NULL, 'word40', 'Obnovit verzi', 'Restore version', '', NULL, NULL, NULL),
(41, 0, NULL, 'word41', 'Importovat soubor', 'Import file', '', NULL, NULL, NULL),
(42, 0, NULL, 'word42', 'Nastavení importu', 'Import settings', '', NULL, NULL, NULL),
(43, 0, NULL, 'word43', 'Možnosti importu', 'Import options', '', NULL, NULL, NULL),
(44, 0, NULL, 'word44', 'Smazat vše a vložit znovu', 'Erase everything and insert again', '', NULL, NULL, NULL),
(45, 0, NULL, 'word45', 'Pouze vložit nové záznamy', 'Only insert new records', '', NULL, NULL, NULL),
(46, 0, NULL, 'word46', 'Pouze aktualizovat stávající záznam', 'Simply update the existing record', '', NULL, NULL, NULL),
(47, 0, NULL, 'word47', 'Vložit nové záznamy a aktualizovat stávající záznamy', 'Insert new records and update existing records', '', NULL, NULL, NULL),
(48, 0, NULL, 'word48', 'Upravit', 'Edit', '', NULL, NULL, NULL),
(49, 0, NULL, 'word49', 'Odstranit', 'Delete', '', NULL, NULL, NULL),
(50, 0, NULL, 'word50', 'Opravdu si přeje odstranit', 'Are you sure you want to remove', '', NULL, NULL, NULL),
(51, 0, NULL, 'word51', 'Nejsou dostupná žádná data', 'No data available', '', NULL, NULL, NULL),
(52, 0, NULL, 'word52', 'Přidat', 'Add', '', NULL, NULL, NULL),
(53, 0, NULL, 'word53', 'Odstranit', 'Delete', '', NULL, NULL, NULL),
(54, 0, NULL, 'word54', 'Opravdu si přejete provést zvolenou operaci', 'Do you really want to perform the selected operation', '', NULL, NULL, NULL),
(55, 0, NULL, 'word55', 'Kopírovat', 'Copy', '', NULL, NULL, NULL),
(56, 0, NULL, 'word56', 'Kopírovat vybrané', 'Copy selected', '', NULL, NULL, NULL),
(57, 0, NULL, 'word57', 'Opravdu si přejete zkopírovat vybrané položky', 'Do you really want to copy the selected item', '', NULL, NULL, NULL),
(58, 0, NULL, 'word58', 'Exportovat vše', 'Export all', '', NULL, NULL, NULL),
(59, 0, NULL, 'word59', 'Importovat', 'Import', '', NULL, NULL, NULL),
(60, 0, NULL, 'word60', 'Vyhledat', 'Search', '', NULL, NULL, NULL),
(61, 0, NULL, 'word61', 'Zrušit', 'Cancel', '', NULL, NULL, NULL),
(62, 0, NULL, 'word62', 'Odstraněné položky', 'Deleted items', '', NULL, NULL, NULL),
(63, 0, NULL, 'word63', 'Zpět', 'Back', '', NULL, NULL, NULL),
(64, 0, NULL, 'word64', 'Obnovit položku', 'Restore item', '', NULL, NULL, NULL),
(65, 0, NULL, 'word65', 'Opravdu si přejete obnovit', 'Do you really want to restore', '', NULL, NULL, NULL),
(66, 0, NULL, 'word66', 'Obnovit vybrané', 'Restore selected', '', NULL, NULL, NULL),
(67, 0, NULL, 'word67', 'Opravdu si přejete obnovit vybrané položky', 'Do you really want to restore the selected item', '', NULL, NULL, NULL),
(68, 0, NULL, 'word68', 'Historie pložky', 'History item', '', NULL, NULL, NULL),
(69, 0, NULL, 'word69', 'Editace webu', 'Editing the web', '', NULL, NULL, NULL),
(70, 0, NULL, 'word70', 'Website Admin', 'Website Admin', '', NULL, NULL, NULL),
(71, 0, NULL, 'word71', 'Přihlášení do systému', 'Login to the system', '', NULL, NULL, NULL),
(72, 0, NULL, 'word72', 'Výběr webu a jazyka', 'Site selection and language', '', NULL, NULL, NULL),
(73, 0, NULL, 'word73', 'Seznam webů', 'List of web sites', '', NULL, NULL, NULL),
(74, 0, NULL, 'word74', 'Web', 'Web', '', NULL, NULL, NULL),
(75, 0, NULL, 'word75', 'Seznam jazyků', 'List of languages', '', NULL, NULL, NULL),
(76, 0, NULL, 'word76', 'Jazyk', 'Language', '', NULL, NULL, NULL),
(77, 0, NULL, 'word77', 'Seznam  slov', 'The list of words', '', NULL, NULL, NULL),
(78, 0, NULL, 'word78', 'Jméno skupiny', 'Group name', '', NULL, NULL, NULL),
(79, 0, NULL, 'word79', 'Povolené jazyky administrace', 'Enabled languages administration', '', NULL, NULL, NULL),
(80, 0, NULL, 'word80', 'Jméno jazyka', 'Name language', '', NULL, NULL, NULL),
(81, 0, NULL, 'word81', 'Identifikátor', 'Identifier', '', NULL, NULL, NULL),
(82, 0, NULL, 'word82', 'Zadejte název jazyka', 'Enter the name of the language', '', NULL, NULL, NULL),
(83, 0, NULL, 'word83', 'Zadejte identifikátor', 'Enter the identifier', '', NULL, NULL, NULL),
(84, 0, NULL, 'word84', 'Identifikátor již existuje', 'Identifier already exists', '', NULL, NULL, NULL),
(85, 0, NULL, 'word85', 'Zadejte název jazyka', 'Enter the name of the language', '', NULL, NULL, NULL),
(86, 0, NULL, 'word86', 'Zadejte ROOTURL', 'enter ROOTURL', '', NULL, NULL, NULL),
(87, 0, NULL, 'word87', 'URL již existuje', 'URL already exists', '', NULL, NULL, NULL),
(88, 0, NULL, 'word88', 'Zadejte název webu', 'Enter the site name', '', NULL, NULL, NULL),
(89, 0, NULL, 'word89', 'Web již existuje', 'Web already exists', '', NULL, NULL, NULL),
(90, 0, NULL, 'word90', 'Zadejte název skupiny', 'Enter the group name', '', NULL, NULL, NULL),
(91, 0, NULL, 'word91', 'Skupina již existuje', 'The group already exists', '', NULL, NULL, NULL),
(92, 0, NULL, 'word92', 'Skupina', 'Group', '', NULL, NULL, NULL),
(93, 0, NULL, 'word93', 'zde', 'here', '', NULL, NULL, NULL),
(94, 0, NULL, 'word94', 'Nastavení administace', 'Administration settings', '', NULL, NULL, NULL),
(95, 0, NULL, 'word95', 'Nastavení webů', 'Setting the web', '', NULL, NULL, NULL),
(96, 0, NULL, 'word96', 'Nastavení jazyků', 'Setting the language', '', NULL, NULL, NULL),
(97, 0, NULL, 'word97', 'Jazyky administrace', 'Languages administration', '', NULL, NULL, NULL),
(98, 0, NULL, 'word98', 'Nastavení slov', 'Setting words', '', NULL, NULL, NULL),
(99, 0, NULL, 'word99', 'Odhlásit se', 'Log out', '', NULL, NULL, NULL),
(100, 0, NULL, 'word100', 'Média', 'Media', '', NULL, NULL, NULL),
(101, 0, NULL, 'word101', 'Úložiště souborů', 'File storage', '', NULL, NULL, NULL),
(102, 0, NULL, 'word102', 'Úložiště souborů', 'File storage', '', NULL, NULL, NULL),
(103, 0, NULL, 'word103', 'Nová složka', 'New folder', '', NULL, NULL, NULL),
(104, 0, NULL, 'word104', 'Nahrát soubor', 'Upload a file', '', NULL, NULL, NULL),
(105, 0, NULL, 'word105', 'Stáhnout soubor', 'Download a file', '', NULL, NULL, NULL),
(106, 0, NULL, 'word106', 'Zobrazit náhled', 'Show preview', '', NULL, NULL, NULL),
(107, 0, NULL, 'word107', 'Přesunout', 'Move', '', NULL, NULL, NULL),
(108, 0, NULL, 'word108', 'Kopírovat', 'Copy', '', NULL, NULL, NULL),
(109, 0, NULL, 'word109', 'Smazat', 'Delete', '', NULL, NULL, NULL),
(110, 0, NULL, 'word110', 'Vlastnosti', 'Properties', '', NULL, NULL, NULL),
(111, 0, NULL, 'word111', 'Nová složka', 'New folder', '', NULL, NULL, NULL),
(112, 0, NULL, 'word112', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(113, 0, NULL, 'word113', 'Přístupová práva', 'Access rights', '', NULL, NULL, NULL),
(114, 0, NULL, 'word114', 'Jméno složky', 'Folder name', '', NULL, NULL, NULL),
(115, 0, NULL, 'word115', 'Nahrání souboru do úložiště', 'Uploading files to the repository', '', NULL, NULL, NULL),
(116, 0, NULL, 'word116', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(117, 0, NULL, 'word117', 'Přístupová práva', 'Access rights', '', NULL, NULL, NULL),
(118, 0, NULL, 'word118', 'Vyberte soubor', 'Select the file', '', NULL, NULL, NULL),
(119, 0, NULL, 'word119', 'Aktualizace smazaných záznamů není povolena', 'Update deleted records is not allowed', '', NULL, NULL, NULL),
(120, 0, NULL, 'word120', 'Není vybrán žádný objekt', 'There is no object', '', NULL, NULL, NULL),
(121, 0, NULL, 'word121', 'Přesně obsahuje', 'Exactly contains', '', NULL, NULL, NULL),
(122, 0, NULL, 'word122', 'Začíná', 'Begins', '', NULL, NULL, NULL),
(123, 0, NULL, 'word123', 'Končí', 'Ends', '', NULL, NULL, NULL),
(124, 0, NULL, 'word124', 'Obsahuje', 'Contains', '', NULL, NULL, NULL),
(125, 0, NULL, 'word125', 'Neobsahuje přesně', 'Does not exactly', '', NULL, NULL, NULL),
(126, 0, NULL, 'word126', 'Nezačíná', 'Does not begin', '', NULL, NULL, NULL),
(127, 0, NULL, 'word127', 'Nekončí', 'Does not ends', '', NULL, NULL, NULL),
(128, 0, NULL, 'word128', 'Neobsahuje', 'Does not contain', '', NULL, NULL, NULL),
(129, 0, NULL, 'word129', 'a zároveň', 'while', '', NULL, NULL, NULL),
(130, 0, NULL, 'word130', 'nebo', 'or', '', NULL, NULL, NULL),
(131, 0, NULL, 'word131', 'Moduly', 'Modules', '', NULL, NULL, NULL),
(132, 0, NULL, 'word132', 'Přiřadit jazyk', 'Assign language', '', NULL, NULL, NULL),
(133, 0, NULL, 'word133', 'Nainstalované moduly', 'Installed modules', '', NULL, NULL, NULL),
(134, 0, NULL, 'word134', 'Vybrat', 'Choose', '', NULL, NULL, NULL),
(135, 0, NULL, 'word135', 'Editace webu', 'Editing the web', '', NULL, NULL, NULL),
(136, 0, NULL, 'word136', 'Obsah webu', 'Site content', '', NULL, NULL, NULL),
(137, 0, NULL, 'word137', 'Šablony', 'Templates', '', NULL, NULL, NULL),
(138, 0, NULL, 'word138', 'Editace šablon webu', 'Editing the web templates', '', NULL, NULL, NULL),
(139, 0, NULL, 'word139', 'Uživatelské účty', 'User accounts', '', NULL, NULL, NULL),
(140, 0, NULL, 'word140', 'Správa uživatelských účtů', 'Managing user accounts', '', NULL, NULL, NULL),
(141, 0, NULL, 'word141', 'Uživatelské skupiny', 'User groups', '', NULL, NULL, NULL),
(142, 0, NULL, 'word142', 'Správa uživatelských skupin', 'User rights management', '', NULL, NULL, NULL),
(143, 0, NULL, 'word143', 'Můj profil', 'My profile', '', NULL, NULL, NULL),
(144, 0, NULL, 'word144', 'Editace mého profilu', 'Editing my profile', '', NULL, NULL, NULL),
(145, 0, NULL, 'word145', 'Uživatelé', 'Users', '', NULL, NULL, NULL),
(146, 0, NULL, 'word146', 'Galerie', 'Gallery', '', NULL, NULL, NULL),
(147, 0, NULL, 'word147', 'Audio', 'Audio', '', NULL, NULL, NULL),
(148, 0, NULL, 'word148', 'Video', 'Video', '', NULL, NULL, NULL),
(149, 0, NULL, 'word149', 'Content', 'Content', '', NULL, NULL, NULL),
(150, 0, NULL, 'word150', 'Zadejte jméno modulu', 'Enter the name of the module', '', NULL, NULL, NULL),
(151, 0, NULL, 'word151', 'Zadejte skupinu modulu', 'Enter the group module', '', NULL, NULL, NULL),
(152, 0, NULL, 'word152', 'Zadejte jméno modulu', 'Enter the name of the module', '', NULL, NULL, NULL),
(153, 0, NULL, 'word153', 'Zobrazované jméno modulu', 'Display name module', '', NULL, NULL, NULL),
(154, 0, NULL, 'word154', 'Skupina modulu', 'Group module', '', NULL, NULL, NULL),
(155, 0, NULL, 'word155', 'Jméno modulu', 'Module name', '', NULL, NULL, NULL),
(156, 0, NULL, 'word156', 'Přidat modul', 'Add module', '', NULL, NULL, NULL),
(157, 0, NULL, 'word157', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(158, 0, NULL, 'word158', 'Zobrazené jméno modulu', 'Display name module', '', NULL, NULL, NULL),
(159, 0, NULL, 'word159', 'Skupina modulu', 'Group module', '', NULL, NULL, NULL),
(160, 0, NULL, 'word160', 'Jméno modulu', 'Module name', '', NULL, NULL, NULL),
(161, 0, NULL, 'word161', 'Přiřazené slovo', 'Assigned word', '', NULL, NULL, NULL),
(162, 0, NULL, 'word162', 'Vyberte …', 'Choose ...', '', NULL, NULL, NULL),
(163, 0, NULL, 'word163', 'Výběr webu a jazyka', 'Site selection and language', '', NULL, NULL, NULL),
(164, 0, NULL, 'word164', 'Jméno skupiny', 'Group name', '', NULL, NULL, NULL),
(165, 0, NULL, 'word165', 'Přidání skupiny', 'Add a group', '', NULL, NULL, NULL),
(166, 0, NULL, 'word166', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(167, 0, NULL, 'word167', 'Jméno skupiny', 'Group name', '', NULL, NULL, NULL),
(168, 0, NULL, 'word168', 'Identifikátor skupiny', 'Group identifier', '', NULL, NULL, NULL),
(169, 0, NULL, 'word169', 'Systémová skupina', 'System group', '', NULL, NULL, NULL),
(170, 0, NULL, 'word170', 'Uživatelské jméno', 'Username', '', NULL, NULL, NULL),
(171, 0, NULL, 'word171', 'Jméno', 'Name', '', NULL, NULL, NULL),
(172, 0, NULL, 'word172', 'Příjmení', 'Surname', '', NULL, NULL, NULL),
(173, 0, NULL, 'word173', 'Email', 'Email', '', NULL, NULL, NULL),
(174, 0, NULL, 'word174', 'Přidání uživatele', 'Add user', '', NULL, NULL, NULL),
(175, 0, NULL, 'word175', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(176, 0, NULL, 'word176', 'Uživatelské jméno', 'Username', '', NULL, NULL, NULL),
(177, 0, NULL, 'word177', 'Jméno', 'Name', '', NULL, NULL, NULL),
(178, 0, NULL, 'word178', 'Příjmení', 'Surname', '', NULL, NULL, NULL),
(179, 0, NULL, 'word179', 'Email', 'Email', '', NULL, NULL, NULL),
(180, 0, NULL, 'word180', 'Heslo', 'Password', '', NULL, NULL, NULL),
(181, 0, NULL, 'word181', 'Hlavní skupina', 'Main group', '', NULL, NULL, NULL),
(182, 0, NULL, 'word182', 'Povolené weby', 'Allowed sites', '', NULL, NULL, NULL),
(183, 0, NULL, 'word183', 'Povolené moduly', 'Enabled modules', '', NULL, NULL, NULL),
(184, 0, NULL, 'word184', 'Uživatelské číselníky', 'Users dials', '', NULL, NULL, NULL),
(185, 0, NULL, 'word185', 'Zadejte jméno číselníku', 'Enter the name of the dial', '', NULL, NULL, NULL),
(186, 0, NULL, 'word186', 'Zadejte identifikátor číselníku', 'Enter the ID code list', '', NULL, NULL, NULL),
(187, 0, NULL, 'word187', 'Identifikátor číselníku již existuje', 'Dial identifier already exists', '', NULL, NULL, NULL),
(188, 0, NULL, 'word188', 'Uživatelské číselníky', 'Users dials', '', NULL, NULL, NULL),
(189, 0, NULL, 'word189', 'Jméno číselníku', 'The name of the dial', '', NULL, NULL, NULL),
(190, 0, NULL, 'word190', 'Identifikátor', 'Identifier', '', NULL, NULL, NULL),
(191, 0, NULL, 'word191', 'Detail číselníku', 'Detail dial', '', NULL, NULL, NULL),
(192, 0, NULL, 'word192', 'Jméno číselníku', 'The name of the dial', '', NULL, NULL, NULL),
(193, 0, NULL, 'word193', 'Identifikátor', 'Identifier', '', NULL, NULL, NULL),
(194, 0, NULL, 'word194', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(195, 0, NULL, 'word195', 'Položky číselníku', 'Items dial', '', NULL, NULL, NULL),
(196, 0, NULL, 'word196', 'Přístup odepřen', 'Access denied', '', NULL, NULL, NULL),
(197, 0, NULL, 'word197', 'Nemáte přístup k tomuto modulu', 'You do not have access to this model', '', NULL, NULL, NULL),
(198, 0, NULL, 'word198', 'Data číselníku', 'Data dial', '', NULL, NULL, NULL),
(199, 0, NULL, 'word199', 'Název hodnoty', 'Name value', '', NULL, NULL, NULL),
(200, 0, NULL, 'word200', 'Typ hodnoty', 'Value type', '', NULL, NULL, NULL),
(201, 0, NULL, 'word201', 'Přidání položky do číselníku', 'Adding items to the dial', '', NULL, NULL, NULL),
(202, 0, NULL, 'word202', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(203, 0, NULL, 'word203', 'Zobrazované jméno', 'Show name', '', NULL, NULL, NULL),
(204, 0, NULL, 'word204', 'Identifikátor', 'Identifier', '', NULL, NULL, NULL),
(205, 0, NULL, 'word205', 'Typ položky', 'Item type', '', NULL, NULL, NULL),
(206, 0, NULL, 'word206', 'Zobrazit v administraci', 'Show in administration', '', NULL, NULL, NULL),
(207, 0, NULL, 'word207', 'Zobrazit na webu', 'View on the web', '', NULL, NULL, NULL),
(208, 0, NULL, 'word208', 'Výchozí hodnota', 'The default value', '', NULL, NULL, NULL),
(209, 0, NULL, 'word209', 'Minimální délka', 'Minimum length', '', NULL, NULL, NULL),
(210, 0, NULL, 'word210', 'Maximální délka', 'The maximum length', '', NULL, NULL, NULL),
(211, 0, NULL, 'word211', 'Povinná položka', 'Required field', '', NULL, NULL, NULL),
(212, 0, NULL, 'word212', 'Textové pole', 'Text field', '', NULL, NULL, NULL),
(213, 0, NULL, 'word213', 'Vyberte …', 'Choose ...', '', NULL, NULL, NULL),
(214, 0, NULL, 'word214', 'Výběr M z N', 'Selection of M N', '', NULL, NULL, NULL),
(215, 0, NULL, 'word215', 'Výběr 1 z n', 'Selecting one of n', '', NULL, NULL, NULL),
(216, 0, NULL, 'word216', 'Výběr barvy', 'Color selection', '', NULL, NULL, NULL),
(217, 0, NULL, 'word217', 'Email', 'E-mail', '', NULL, NULL, NULL),
(218, 0, NULL, 'word218', 'Soubor', 'File', '', NULL, NULL, NULL),
(219, 0, NULL, 'word219', 'Skryté pole', 'Hidden field', '', NULL, NULL, NULL),
(220, 0, NULL, 'word220', 'Číslo', 'Nubmers', '', NULL, NULL, NULL),
(221, 0, NULL, 'word221', 'Heslo', 'Passowrd', '', NULL, NULL, NULL),
(222, 0, NULL, 'word222', 'Posuvník', 'Slider', '', NULL, NULL, NULL),
(223, 0, NULL, 'word223', 'Vyhledávání', 'Search', '', NULL, NULL, NULL),
(224, 0, NULL, 'word224', 'Telefonní číslo', 'Phonenumber', '', NULL, NULL, NULL),
(225, 0, NULL, 'word225', 'Url adresa', 'URL', '', NULL, NULL, NULL),
(226, 0, NULL, 'word226', 'Můj profil', 'My profile', '', NULL, NULL, NULL),
(227, 0, NULL, 'word227', 'Zadejte jméno položky', 'Enter the name of the item', '', NULL, NULL, NULL),
(228, 0, NULL, 'word228', 'Zadejte identifikátor položky', 'Enter item identifier', '', NULL, NULL, NULL),
(229, 0, NULL, 'word229', 'Identifikátor musí být unikátní', 'The identifier must be unique', '', NULL, NULL, NULL),
(230, 0, NULL, 'word230', 'Zvolte typ položky', 'Choose the type of item', '', NULL, NULL, NULL),
(231, 0, NULL, 'word231', 'Hodnoty', 'Values', '', NULL, NULL, NULL),
(232, 0, NULL, 'word232', 'Uložit', 'Save', '', NULL, NULL, NULL),
(233, 0, NULL, 'word233', 'Zahodit změny', 'Discard changes', '', NULL, NULL, NULL),
(234, 0, NULL, 'word234', 'Nový objekt', 'Folder', '', '', NULL, NULL),
(235, 0, NULL, 'word235', 'Detail', 'Detail', '', NULL, NULL, NULL),
(236, 0, NULL, 'word236', 'Detail objektu', 'Detail of item', '', NULL, NULL, NULL),
(237, 0, NULL, 'word237', 'Obecné nastavení', 'General settings', '', NULL, NULL, NULL),
(238, 0, NULL, 'word238', 'Jméno objektu', 'Object name', '', NULL, NULL, NULL),
(239, 0, NULL, 'word239', 'SEO URL', 'SEO URL', '', NULL, NULL, NULL),
(240, 0, NULL, 'word240', 'Přístupné přes SEO URL', 'Accessible via SEO URL', '', NULL, NULL, NULL),
(241, 0, NULL, 'word241', 'Přiřazená šablona', 'Assigned template', '', NULL, NULL, NULL),
(242, 0, NULL, 'word242', 'Nezařazovat do vyhledávání', 'Not include search', '', NULL, NULL, NULL),
(243, 0, NULL, 'word243', 'Identifikátor', 'Identifier', '', NULL, NULL, NULL),
(244, 0, NULL, 'word244', 'Oprávnění', 'Authorization', '', NULL, NULL, NULL),
(245, 0, NULL, 'word245', 'Číst', 'Read', '', NULL, NULL, NULL),
(246, 0, NULL, 'word246', 'Editovat', 'Edit', '', NULL, NULL, NULL),
(247, 0, NULL, 'word247', 'Mazat', 'Delete', '', NULL, NULL, NULL),
(248, 0, NULL, 'word248', 'Publikace', 'Publications', '', NULL, NULL, NULL),
(249, 0, NULL, 'word249', 'Změna práv', 'Variation of rights', '', NULL, NULL, NULL),
(250, 0, NULL, 'word250', 'Související položky', 'Related items', '', NULL, NULL, NULL),
(251, 0, NULL, 'word251', 'Diskuze', 'Discussion', '', NULL, NULL, NULL),
(252, 0, NULL, 'word252', 'Media galerie', 'Media gallery', '', NULL, NULL, NULL),
(253, 0, NULL, 'word253', 'Možnosti fotogalerie', 'Options gallery', '', NULL, NULL, NULL),
(254, 0, NULL, 'word254', 'Článek má vlastní fotogalerii', 'Article has its own photo gallery', '', NULL, NULL, NULL),
(255, 0, NULL, 'word255', 'Zkopírovat galerii z jiné článku', 'Copy gallery from another article', '', NULL, NULL, NULL),
(256, 0, NULL, 'word256', 'Používat galerii z jiného článku', 'Use the gallery from another article', '', NULL, NULL, NULL),
(257, 0, NULL, 'word257', 'Možnosti diskuze', 'Options discussion', '', NULL, NULL, NULL),
(258, 0, NULL, 'word258', 'Nepoužívat diskuzi', 'Do not use discussion', '', NULL, NULL, NULL),
(259, 0, NULL, 'word259', 'Článek má vlastní diskuzi', 'Article has its own discussion', '', NULL, NULL, NULL),
(260, 0, NULL, 'word260', 'Zkopírovat diskuzi z jiného článku', 'Copy the discussion of another article', '', NULL, NULL, NULL),
(261, 0, NULL, 'word261', 'Připojit diskuzi z jiného článku', 'Join discussion for another article', '', NULL, NULL, NULL),
(262, 0, NULL, 'word262', 'Připojit fotografii', 'Attach image', '', NULL, NULL, NULL),
(263, 0, NULL, 'word263', 'Připojit video', 'Attach movie', '', NULL, NULL, NULL),
(264, 0, NULL, 'word264', 'Připojit audio soubor', 'Attach audio file', '', NULL, NULL, NULL),
(265, 0, NULL, 'word265', 'Připojit soubor', 'Attach file', '', NULL, NULL, NULL),
(266, 0, NULL, 'word266', 'Galerii lze připojit pouze k uloženému objektu', 'Gallery can only connect to the stored object', '', NULL, NULL, NULL),
(267, 0, NULL, 'word267', 'Diskuzi lze připojit pouze k uloženému objektu', 'Discussion can only connect to the stored object', '', NULL, NULL, NULL),
(268, 0, NULL, 'word268', 'Přidat novou šablonu', 'Add new template', '', NULL, NULL, NULL),
(269, 0, NULL, 'word269', 'Editace šablony', 'Editing templates', '', NULL, NULL, NULL),
(270, 0, NULL, 'word270', 'Html editor', 'Html editor', '', NULL, NULL, NULL),
(271, 0, NULL, 'word271', 'Upravit', 'Edit', '', NULL, NULL, NULL),
(272, 0, NULL, 'word272', 'Smazat šablonu', 'Delete template', '', NULL, NULL, NULL),
(273, 0, NULL, 'word273', 'Připojený číselník', 'Connected dial', '', NULL, NULL, NULL),
(274, 0, NULL, 'word274', 'Nadřazená šablona', 'Parent template', '', NULL, NULL, NULL),
(275, 0, NULL, 'word275', 'Uložit a publikovat', 'Save and publish', '', NULL, NULL, NULL),
(276, 0, NULL, 'word276', 'Opravdu si přejete odstranit šablonu', 'Are you sure you want to delete a template', '', NULL, NULL, NULL),
(277, 0, NULL, 'word277', 'Hlavička', 'Header', '', NULL, NULL, NULL),
(278, 0, NULL, 'word278', 'Titulek stránky', 'The page title', '', NULL, NULL, NULL),
(279, 0, NULL, 'word279', 'Klíčová slova', 'Keywords', '', NULL, NULL, NULL),
(280, 0, NULL, 'word280', 'Popis stránky', 'Description page', '', NULL, NULL, NULL),
(281, 0, NULL, 'word281', 'Kategorie stránek', 'Category pages', '', NULL, NULL, NULL),
(282, 0, NULL, 'word282', 'CSS styly', 'CSS styles', '', NULL, NULL, NULL),
(283, 0, NULL, 'word283', 'Nový css styl', 'New CSS style', '', NULL, NULL, NULL),
(284, 0, NULL, 'word284', 'Upravit css', 'Edit css', '', NULL, NULL, NULL),
(285, 0, NULL, 'word285', 'Opravdu si přejete odstranit', 'Are you sure you want to remove', '', NULL, NULL, NULL),
(286, 0, NULL, 'word286', 'Odstranit css', 'Remove css', '', NULL, NULL, NULL),
(287, 0, NULL, 'word287', 'CSS webu', 'CSS web', '', NULL, NULL, NULL),
(288, 0, NULL, 'word288', 'CSS editor', 'CSS editor', '', NULL, NULL, NULL),
(289, 0, NULL, 'word289', 'Zdrojový kód', 'Source code', '', NULL, NULL, NULL),
(290, 0, NULL, 'word290', 'Zobrazovat od', 'View from', '', NULL, NULL, NULL),
(291, 0, NULL, 'word291', 'Zobrazovat do', 'View to', '', NULL, NULL, NULL),
(292, 0, NULL, 'word292', 'Parametry', 'Parameters', '', NULL, NULL, NULL),
(293, 0, NULL, 'word293', 'Víceřádkový text', 'Multiline text', '', NULL, NULL, NULL),
(294, 0, NULL, 'word294', 'Html editor', 'Html editor', '', NULL, NULL, NULL),
(295, 0, NULL, 'word295', 'Kalendář', 'Calendar', '', NULL, NULL, NULL),
(296, 0, NULL, 'word296', 'Hodnoty', 'Values', '', NULL, NULL, NULL),
(297, 0, NULL, 'word297', 'Nová možnost', 'New item', '', NULL, NULL, NULL),
(298, 0, NULL, 'word298', 'Editovat možnost', 'Edit item', '', NULL, NULL, NULL),
(299, 0, NULL, 'word299', 'Smazat možnost', 'Delete item', '', NULL, NULL, NULL),
(300, 0, NULL, 'word300', 'Hodnota', 'Value', '', NULL, NULL, NULL),
(301, 0, NULL, 'word301', 'Zobrazovaný text', 'Display text', '', NULL, NULL, NULL),
(302, 0, NULL, 'word302', 'Uložit', 'Save', '', NULL, NULL, NULL),
(303, 0, NULL, 'word303', 'Zrušit', 'Cancel', '', NULL, NULL, NULL),
(304, 0, NULL, 'word304', 'Opravdu si přejete smazat?', 'Are you sure you want to delete?', '', NULL, NULL, NULL),
(305, 0, NULL, 'word305', 'Nástroje pro vývojáře', 'Developer tools', '', NULL, NULL, NULL),
(306, 0, NULL, 'word306', 'Přidání jazyka provedete kliknutím', 'Adding the language by clicking', '', NULL, NULL, NULL),
(307, 0, NULL, 'word307', 'zde', 'here', '', NULL, NULL, NULL),
(308, 0, NULL, 'word308', 'Objekty', 'Objects', '', NULL, NULL, NULL),
(309, 0, NULL, 'word309', 'Soubory z úložiště', 'Files from the repository', '', NULL, NULL, NULL),
(310, 0, NULL, 'word310', 'Externí odkazy', 'External links', '', NULL, NULL, NULL),
(311, 0, NULL, 'word311', 'Formuláře', 'Forms', '', NULL, NULL, NULL),
(312, 0, NULL, 'word312', 'Jméno odkazu:', 'Name link:', '', NULL, NULL, NULL),
(313, 0, NULL, 'word313', 'Url:', 'Url:', '', NULL, NULL, NULL),
(314, 0, NULL, 'word314', 'Nahrát soubor', 'Upload a file', '', NULL, NULL, NULL),
(315, 0, NULL, 'word315', 'Kopírovat', 'Copy', '', NULL, NULL, NULL),
(316, 0, NULL, 'word316', 'Přesunout', 'Move', '', NULL, NULL, NULL),
(317, 0, NULL, 'word317', 'Odstranit', 'Delete', '', NULL, NULL, NULL),
(318, 0, NULL, 'word318', 'Odstranění', 'Removal', '', NULL, NULL, NULL),
(319, 0, NULL, 'word319', 'Opravdu si přejete odstranit', 'Are you sure you want to remove', '', NULL, NULL, NULL),
(320, 0, NULL, 'word320', 'Vyberte složku', 'Select the folder', '', NULL, NULL, NULL),
(321, 0, NULL, 'word321', 'Přístup omezen zkuste to za 15 minut', 'Access restricted try again in 15 minutes', '', NULL, NULL, NULL),
(322, 0, NULL, 'word322', 'Exportovat obsah', 'Export content', '', NULL, NULL, NULL),
(323, 0, NULL, 'word323', 'Exportovat šablony', 'Export templates', '', NULL, NULL, NULL),
(324, 0, NULL, 'word324', 'Exportovat css', 'Export css', '', NULL, NULL, NULL),
(325, 0, NULL, 'word325', 'Exportovat js', 'Export js', '', NULL, NULL, NULL),
(326, 0, NULL, 'word326', 'Exportovat js', 'Export js', '', NULL, NULL, NULL),
(327, 0, NULL, 'word327', 'Exportovat emaily', 'Export e-mails', '', NULL, NULL, NULL),
(328, 0, NULL, 'word328', 'Exportovat repository', 'Export repository', '', NULL, NULL, NULL),
(329, 0, NULL, 'word329', 'Exportovat uživatele', 'Export users', '', NULL, NULL, NULL),
(330, 0, NULL, 'word330', 'Exportovat uživatelské skupiny', 'Export user groups', '', NULL, NULL, NULL),
(331, 0, NULL, 'word331', 'Exportovat weby', 'Export sites', '', NULL, NULL, NULL),
(332, 0, NULL, 'word332', 'Exportovat jazykové mutace', 'Export language versions', '', NULL, NULL, NULL),
(333, 0, NULL, 'word333', 'Exportovat jazyky administrace', 'Languages export administration', '', NULL, NULL, NULL),
(334, 0, NULL, 'word334', 'Exportovat slova', 'Export words', '', NULL, NULL, NULL),
(335, 0, NULL, 'word335', 'Exportovat moduly', 'Export modules', '', NULL, NULL, NULL),
(336, 0, NULL, 'word336', 'Exportovat uživatelské číselníky', 'Export user dials', '', NULL, NULL, NULL),
(337, 0, NULL, 'word337', 'Vyexportovat', 'Export', '', NULL, NULL, NULL),
(338, 0, NULL, 'word338', 'Zablokované funkce uživatele', 'Blocked user functions', '', NULL, NULL, NULL),
(339, 0, NULL, 'word339', 'Změna hesla', 'Changing the password', '', NULL, NULL, NULL),
(340, 0, NULL, 'word340', 'Vyberte', 'Select', '', NULL, NULL, NULL),
(341, 0, NULL, 'word341', 'Aktivní uživatel', 'Active users', '', NULL, NULL, NULL),
(342, 0, NULL, 'word342', 'Zablokovat přidávání příspěvků do diskuze', 'Block posting discussion', '', NULL, NULL, NULL),
(343, 0, NULL, 'word343', 'Nové heslo:', 'New password:', '', NULL, NULL, NULL),
(344, 0, NULL, 'word344', 'Nové heslo znovu:', 'New password again:', '', NULL, NULL, NULL),
(345, 0, NULL, 'word345', 'Změnit heslo', 'Change password', '', NULL, NULL, NULL),
(346, 0, NULL, 'word346', 'Povolit přímou editaci hodnot', 'Allow direct editing of values', '', NULL, NULL, NULL),
(347, 0, NULL, 'word347', 'Systémový číselník', 'System dial', '', NULL, NULL, NULL),
(348, 0, NULL, 'word348', 'Data z číselníku', 'Data from dial', '', NULL, NULL, NULL),
(349, 0, NULL, 'word349', 'V administraci pouze ke čtení', 'In the administration read only', '', NULL, NULL, NULL),
(350, 0, NULL, 'word350', 'Na webu pouze ke čtení', 'On the web read-only', '', NULL, NULL, NULL),
(351, 0, NULL, 'word351', 'Validace', 'Validation', '', NULL, NULL, NULL),
(352, 0, NULL, 'word352', 'Css styl', 'CSS style', '', NULL, NULL, NULL),
(353, 0, NULL, 'word353', 'Další html atributy', 'Other html attributes', '', NULL, NULL, NULL),
(354, 0, NULL, 'word354', 'Unikátní hodnota', 'Unique value', '', NULL, NULL, NULL),
(355, 0, NULL, 'word355', 'Data z číselníku', 'Data from dial', '', NULL, NULL, NULL),
(356, 0, NULL, 'word356', 'Možnosti obrázků', 'Picture options', '', NULL, NULL, NULL),
(357, 0, NULL, 'word357', 'Výchozí oprávnění', 'Default permissions', '', NULL, NULL, NULL),
(358, 0, NULL, 'word358', 'Nastavení uživatelů', 'Setting up users', '', NULL, NULL, NULL),
(359, 0, NULL, 'word359', 'Malý obrázek', 'Small image', '', NULL, NULL, NULL),
(360, 0, NULL, 'word360', 'Výška', 'Height', '', NULL, NULL, NULL),
(361, 0, NULL, 'word361', 'Šířka', 'Width', '', NULL, NULL, NULL),
(362, 0, NULL, 'word362', 'Střední obrázek', 'Central image', '', NULL, NULL, NULL),
(363, 0, NULL, 'word363', 'Velký obrázek', 'Big image', '', NULL, NULL, NULL),
(364, 0, NULL, 'word364', 'Uživatele aktivuje administrátor', 'The user activates administrator', '', NULL, NULL, NULL),
(365, 0, NULL, 'word365', 'Uživatel se aktivuje po kliku na odkaz, který mu je zaslán emailem', 'The user activates after clicking on a link that is sent to him by e-mail', '', NULL, NULL, NULL),
(366, 0, NULL, 'word366', 'Uživatel se může přihlašovat přes email', 'The user can subscribe via email', '', NULL, NULL, NULL),
(367, 0, NULL, 'word367', 'Přidat nevhodné slovo', 'Add inappropriate word', '', NULL, NULL, NULL),
(368, 0, NULL, 'word368', 'Importovat', 'Import', '', NULL, NULL, NULL),
(369, 0, NULL, 'word369', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(370, 0, NULL, 'word370', 'Exportovat', 'Export', '', NULL, NULL, NULL),
(371, 0, NULL, 'word371', 'Uložit', 'Save', '', NULL, NULL, NULL),
(372, 0, NULL, 'word372', 'Potvrdit odstranění', 'Confirm remove', '', NULL, NULL, NULL),
(373, 0, NULL, 'word373', 'Ano', 'Yes', '', NULL, NULL, NULL),
(374, 0, NULL, 'word374', 'Ne', 'No', '', NULL, NULL, NULL),
(375, 0, NULL, 'word375', 'Potvrdit odstranění', 'Confirm remove', '', NULL, NULL, NULL),
(376, 0, NULL, 'word376', 'Nic není vybráno', 'None specified', '', NULL, NULL, NULL),
(377, 0, NULL, 'word377', 'Potvrdit obnovení', 'Confirm restore', '', NULL, NULL, NULL),
(378, 0, NULL, 'word378', 'Potvrdit obnovení', 'Confirm restore', '', NULL, NULL, NULL),
(379, 0, NULL, 'word379', 'Nic není vybráno', 'None specified', '', NULL, NULL, NULL),
(380, 0, NULL, 'word380', 'Vytvoření kopie', 'Create a copy', '', NULL, NULL, NULL),
(381, 0, NULL, 'word381', 'Kopírovat', 'Copy', '', NULL, NULL, NULL),
(382, 0, NULL, 'word382', 'Vybrat jazyk', 'Choose language', '', NULL, NULL, NULL),
(383, 0, NULL, 'word383', 'Javascripty', 'Java script', '', NULL, NULL, NULL),
(384, 0, NULL, 'word384', 'Formuláře', 'Forms', '', NULL, NULL, NULL),
(385, 0, NULL, 'word385', 'Předefinované emaily', 'Mail templates', '', NULL, NULL, NULL),
(386, 0, NULL, 'word386', 'Odeslane emaily', 'Sending e-mails', '', NULL, NULL, NULL),
(387, 0, NULL, 'word387', 'Nástoje pro vyvojáře', 'Developer tools', '', NULL, NULL, NULL),
(388, 0, NULL, 'word388', 'Odpojit', 'Disconnect', '', NULL, NULL, NULL),
(389, 0, NULL, 'word389', 'Uložit a publikovat', 'Save and publish', '', NULL, NULL, NULL),
(390, 0, NULL, 'word390', 'Ostatní objekty', 'Other objects', '', NULL, NULL, NULL),
(391, 0, NULL, 'word391', 'Přidat související položku', 'Add related item', '', NULL, NULL, NULL),
(392, 0, NULL, 'word392', 'Souvisejicí objekt', 'Related object', '', NULL, NULL, NULL),
(393, 0, NULL, 'word393', 'Připojit', 'Connect', '', NULL, NULL, NULL),
(394, 0, NULL, 'word394', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(395, 0, NULL, 'word395', 'Převzít diskuzi z jiného článku', 'Take over the discussion in another article', '', NULL, NULL, NULL),
(396, 0, NULL, 'word396', 'Přejít do diskuze', 'Go to discussion', '', NULL, NULL, NULL),
(397, 0, NULL, 'word397', 'Nepoužívat galerii', 'Do not use the gallery', '', NULL, NULL, NULL),
(398, 0, NULL, 'word398', 'Přidat z úložiště', 'Do not use the gallery', '', NULL, NULL, NULL),
(399, 0, NULL, 'word399', 'Převzít gallerii z jiného článku', 'Do not use the gallery', '', NULL, NULL, NULL),
(400, 0, NULL, 'word400', 'Připojit', 'Connect', '', NULL, NULL, NULL),
(401, 0, NULL, 'word401', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(402, 0, NULL, 'word402', 'Položka galerie', 'Item gallery', '', NULL, NULL, NULL),
(403, 0, NULL, 'word403', 'Připojit', 'Connect', '', NULL, NULL, NULL),
(404, 0, NULL, 'word404', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(405, 0, NULL, 'word405', 'Připojený formulář', 'Connection form', '', NULL, NULL, NULL),
(406, 0, NULL, 'word406', 'Vyberte', 'Select', '', NULL, NULL, NULL),
(407, 0, NULL, 'word407', 'Nadpis příspěvku', 'Post title', '', NULL, NULL, NULL),
(408, 0, NULL, 'word408', 'Text příspěvku', 'Message text', '', NULL, NULL, NULL),
(409, 0, NULL, 'word409', 'Datum změny', 'Date of change', '', NULL, NULL, NULL),
(410, 0, NULL, 'word410', 'Přidat příspěvek do diskuze', 'Add contribution to the debate', '', NULL, NULL, NULL),
(411, 0, NULL, 'word411', 'Příspěvky v diskuzi:', 'Add contribution to the debate', '', NULL, NULL, NULL),
(412, 0, NULL, 'word412', 'Přidání příspěvku', 'Adding comment', '', NULL, NULL, NULL),
(413, 0, NULL, 'word413', 'Předmět příspěvku', 'Post subject', '', NULL, NULL, NULL),
(414, 0, NULL, 'word414', 'Vaše jméno', 'Your name', '', NULL, NULL, NULL),
(415, 0, NULL, 'word415', 'Text příspěvku', 'Message text', '', NULL, NULL, NULL),
(416, 0, NULL, 'word416', 'Uložit', 'Save', '', NULL, NULL, NULL),
(417, 0, NULL, 'word417', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(418, 0, NULL, 'word418', 'Historie příspěvku', 'History contribution', '', NULL, NULL, NULL),
(419, 0, NULL, 'word419', 'Uložit a publikovat', 'Save and publish', '', NULL, NULL, NULL),
(420, 0, NULL, 'word420', 'Nastavení formuláře', 'Form settings', '', NULL, NULL, NULL),
(421, 0, NULL, 'word421', 'Statistika formuláře', 'Statistics forms', '', NULL, NULL, NULL),
(422, 0, NULL, 'word422', 'Text tlačítka pro odeslání formuláře', 'Text button to submit the form', '', NULL, NULL, NULL),
(423, 0, NULL, 'word423', 'Css styl tlačítka', 'CSS style buttons', '', NULL, NULL, NULL),
(424, 0, NULL, 'word424', 'Odesílat inforamční email administrátorovi', 'Send the information by e mail administrator', '', NULL, NULL, NULL),
(425, 0, NULL, 'word425', 'Odesílatel emailu', 'The sender email', '', NULL, NULL, NULL),
(426, 0, NULL, 'word426', 'Email administrátora', 'Email administrator', '', NULL, NULL, NULL),
(427, 0, NULL, 'word427', 'Text emailu pro administrátora', 'The text of the e mail administrator', '', NULL, NULL, NULL),
(428, 0, NULL, 'word428', 'Odesílat email zákazníkovi', 'Send email client', '', NULL, NULL, NULL),
(429, 0, NULL, 'word429', 'Text emailu pro zákazníka', 'Text e- mail to the customer', '', NULL, NULL, NULL),
(430, 0, NULL, 'word430', 'Způsob uložení do databáze', 'Method of storing in the database', '', NULL, NULL, NULL),
(431, 0, NULL, 'word431', 'Neukládat', 'Do not save', '', NULL, NULL, NULL),
(432, 0, NULL, 'word432', 'Uložit do statistik formuláře', 'Save to statistics form', '', NULL, NULL, NULL),
(433, 0, NULL, 'word433', 'Zaregistrovat uživatele', 'Register users', '', NULL, NULL, NULL),
(434, 0, NULL, 'word434', 'Přihlásit uživatele', 'User login', '', NULL, NULL, NULL),
(435, 0, NULL, 'word435', 'Akce po odeslání formuláře', 'Events after submitting the form', '', NULL, NULL, NULL),
(436, 0, NULL, 'word436', 'Žádná akce', 'No action', '', NULL, NULL, NULL),
(437, 0, NULL, 'word437', 'Zobrazit text', 'Show text', '', NULL, NULL, NULL),
(438, 0, NULL, 'word438', 'Vyhledat', 'Search', '', NULL, NULL, NULL),
(439, 0, NULL, 'word439', 'Provést reload stránky', 'Perform reload the page', '', NULL, NULL, NULL),
(440, 0, NULL, 'word440', 'Přejít na stránku', 'Go to page', '', NULL, NULL, NULL),
(441, 0, NULL, 'word441', 'Zobrazený text po odeslání formuláře', 'Text displayed after submitting the form', '', NULL, NULL, NULL),
(442, 0, NULL, 'word442', 'Přejít na stránku', 'Go to page', '', NULL, NULL, NULL),
(443, 0, NULL, 'word443', 'Přiřadit odkaz', 'Assign link', '', NULL, NULL, NULL),
(444, 0, NULL, 'word444', 'Automaticky generovat do bootstrapu', 'Automatically generate to bootstrap', '', NULL, NULL, NULL),
(445, 0, NULL, 'word445', 'Připojit k formuláři captchu', 'Connect to form captcha', '', NULL, NULL, NULL),
(446, 0, NULL, 'word446', 'Vyberte', 'Select', '', NULL, NULL, NULL),
(447, 0, NULL, 'word447', 'Připojit', 'Connect', '', NULL, NULL, NULL),
(448, 0, NULL, 'word448', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(449, 0, NULL, 'word449', 'Pozice ve výpisu', 'Position in a statement', '', NULL, NULL, NULL),
(450, 0, NULL, 'word450', 'Uložit a publikovat', 'Save and publish', '', NULL, NULL, NULL),
(451, 0, NULL, 'word451', 'Text emailu', 'Email text', '', NULL, NULL, NULL),
(452, 0, NULL, 'word452', 'Odkaz', 'Link', '', NULL, NULL, NULL),
(453, 0, NULL, 'word453', 'Kopírovat', 'Copy', '', NULL, NULL, NULL),
(454, 0, NULL, 'word454', 'Přesunout', 'Move', '', NULL, NULL, NULL),
(455, 0, NULL, 'word455', 'Odstranit', 'Delete', '', NULL, NULL, NULL),
(456, 0, NULL, 'word456', 'Odstranění', 'Removal', '', NULL, NULL, NULL),
(457, 0, NULL, 'word457', 'Opravdu si přejete odstranit', 'Are you sure you want to remove', '', NULL, NULL, NULL),
(458, 0, NULL, 'word458', 'Ano', 'Yes', '', NULL, NULL, NULL),
(459, 0, NULL, 'word459', 'Ne', 'No', '', NULL, NULL, NULL),
(460, 0, NULL, 'word460', 'Vyberte složku', 'Select the folder', '', NULL, NULL, NULL),
(461, 0, NULL, 'word461', 'Kopírovat', 'Copy', '', NULL, NULL, NULL),
(462, 0, NULL, 'word462', 'Zavřít', 'Close', '', NULL, NULL, NULL),
(463, 0, NULL, 'word463', 'Vyberte', 'Select', '', NULL, NULL, NULL),
(464, 0, NULL, 'word464', 'Vytvořit odkaz', 'Create link', '', NULL, NULL, NULL),
(465, 0, NULL, 'word465', 'Zavřít', 'Clsoe', '', NULL, NULL, NULL),
(466, 0, NULL, 'word466', 'zpět', 'back', '', NULL, NULL, NULL),
(467, 0, NULL, 'word467', 'Editace js', 'Editing js', '', NULL, NULL, NULL),
(468, 0, NULL, 'word468', 'Nový js', 'New js', '', NULL, NULL, NULL),
(469, 0, NULL, 'word469', 'Odstranit js', 'Delete js', '', NULL, NULL, NULL),
(470, 0, NULL, 'word470', 'Formuláře', 'Forms', '', NULL, NULL, NULL),
(471, 0, NULL, 'word471', 'Nový formulář', 'New form', '', NULL, NULL, NULL),
(472, 0, NULL, 'word472', 'Smazat formulář', 'Delete form', '', NULL, NULL, NULL),
(473, 0, NULL, 'word473', 'Předefinované emaily', 'Mailing templates', '', NULL, NULL, NULL),
(474, 0, NULL, 'word474', 'Nový mail', 'New mail', '', NULL, NULL, NULL),
(475, 0, NULL, 'word475', 'Smazat mail', 'Delete mail', '', NULL, NULL, NULL),
(476, 0, NULL, 'word476', 'Upravit js', 'Edit js', '', NULL, NULL, NULL),
(477, 0, NULL, 'word477', 'Upravit formulář', 'Edit form', '', NULL, NULL, NULL),
(478, 0, NULL, 'word478', 'Upravit email', 'Edit mail', '', NULL, NULL, NULL),
(479, 0, NULL, 'word479', 'Odeslané emaily', 'Sent emails', '', NULL, NULL, NULL),
(480, 0, NULL, 'word480', 'Zadejte uživatelské jméno', 'Enter your username', '', NULL, NULL, NULL),
(481, 0, NULL, 'word481', 'Uživatel již existuje', 'User already exists', '', NULL, NULL, NULL),
(482, 0, NULL, 'word482', 'Zadejte jméno', 'Enter the name', '', NULL, NULL, NULL),
(483, 0, NULL, 'word483', 'Zadejte příjmení', 'Enter the last name', '', NULL, NULL, NULL),
(484, 0, NULL, 'word484', 'Zadejte email', 'Enter e-mail', '', NULL, NULL, NULL),
(485, 0, NULL, 'word485', 'Email již existuje', 'E-mail already exists', '', NULL, NULL, NULL),
(486, 0, NULL, 'word486', 'Zadejte heslo', 'Enter password', '', NULL, NULL, NULL),
(487, 0, NULL, 'word487', 'Odstranit', 'Delete', '', NULL, NULL, NULL),
(488, 0, NULL, 'word488', 'Upravit', 'Edit', '', NULL, NULL, NULL),
(489, 0, NULL, 'word489', 'Reagovat', 'Respond', '', NULL, NULL, NULL),
(490, 0, NULL, 'word490', 'Historie příspěvku', 'History contribution', '', NULL, NULL, NULL),
(491, 0, NULL, 'word491', 'Zablokovat přístup do diskuzí tomuto uživateli', 'Block access to the discussions this user', '', NULL, NULL, NULL),
(492, 0, NULL, 'word492', 'Opište', 'Copy', '', NULL, NULL, NULL),
(493, 0, NULL, 'word493', 'Název objektu', 'Object name', '', NULL, NULL, NULL),
(494, 0, NULL, 'word494', 'Odpojit', 'Disconnect', '', NULL, NULL, NULL),
(495, 0, NULL, 'word495', 'Název objektu', 'Object name', '', NULL, NULL, NULL),
(496, 0, NULL, 'word493', 'Název objektu', 'Object name', '', NULL, NULL, NULL),
(497, 0, NULL, 'word494', 'Odpojit', 'Disconnect', '', NULL, NULL, NULL),
(498, 0, NULL, 'word495', 'Název objektu', 'Object name', '', NULL, NULL, NULL),
(499, 0, NULL, 'word496', 'Javascript editor', 'Javascript editor', '', NULL, NULL, NULL),
(500, 0, NULL, 'word497', 'Výchozí jazyk', 'Default language', '', NULL, NULL, NULL),
(501, 0, NULL, 'word498', 'Vyberte', 'Select', '', NULL, NULL, NULL),
(502, 0, NULL, 'word499', 'Odstraněné položky', 'Deleted items', '', NULL, NULL, NULL),
(503, 0, NULL, 'word500', 'Obnovit', 'Restore', '', NULL, NULL, NULL),
(504, 0, NULL, 'word501', 'Jazykové verze', 'Language versions', '', NULL, NULL, NULL),
(505, 0, NULL, 'word502', 'Jazykové verze', 'Language versions', '', NULL, NULL, NULL),
(506, 0, NULL, 'word503', 'Identifikátor jazyka', 'Language identifier', '', NULL, NULL, NULL),
(507, 0, NULL, 'word504', 'existuje', 'exists', '', NULL, NULL, NULL),
(508, 0, NULL, 'word505', 'neexistuje', 'does not exists', '', NULL, NULL, NULL),
(509, 0, NULL, 'word506', 'Zkopírovat jazyk', 'Copy language', '', NULL, NULL, NULL),
(510, 0, NULL, 'word507', 'Zdrojový jazyk', 'Source language', '', NULL, NULL, NULL),
(511, 0, NULL, 'word508', 'Cílový jazyk', 'Target language', '', NULL, NULL, NULL),
(512, 0, NULL, 'word509', 'Zkopírovat', 'Copy', '', NULL, NULL, NULL),
(513, 0, NULL, 'word510', '- kopie', '- copy', '', '', NULL, NULL),
(514, 0, NULL, 'word511', 'Nelze změnit', 'You can not change', '', '', NULL, NULL),
(515, 0, NULL, 'word512', 'Text emailu', 'Email text', '', '', NULL, NULL),
(516, 0, NULL, 'word513', 'Příjemce', 'Recipient', '', '', NULL, NULL),
(517, 0, NULL, 'word514', 'Odesílatel', 'Sender', '', '', NULL, NULL),
(518, 0, NULL, 'word515', 'Čas odeslání', 'Time of departure', '', '', NULL, NULL),
(519, 0, NULL, 'word516', 'IP adresa', 'IP addresses', '', '', NULL, NULL),
(520, 0, NULL, 'word517', 'Znovu poslat emaily', 'Resend email', '', '', NULL, NULL),
(521, 0, NULL, 'word518', 'POZOR! Změnou šablony dojde ke smazání obsahu článku. Přejete si opravdu pokračovat?', 'ATTENTION! By changing templates will delete the contents of the article. Do you really continue?', '', '', NULL, NULL),
(522, 0, NULL, 'word519', 'Zobrazit náhled', 'Show preview', '', '', NULL, NULL),
(523, 0, NULL, 'word520', 'Položka nemůže mít podobjekty', 'Item can have subobjects', '', '', NULL, NULL),
(524, 0, NULL, 'word521', 'Použít šablonu v nových podřízených objektech', 'Use the template in the new child objects', '', '', NULL, NULL),
(525, 0, NULL, 'word522', 'Vyhledat', 'Search', '', '', NULL, NULL),
(526, 0, NULL, 'word523', 'Zrušit filtr', 'Cancel the filter', '', '', NULL, NULL),
(527, 0, NULL, 'word524', 'Zabezpečení', 'Security', '', '', NULL, NULL),
(528, 0, NULL, 'word525', 'Zakázat posílání emailů z webu', 'Block sending e-mail from the web', '', '', NULL, NULL),
(529, 0, NULL, 'word526', 'Zablokovat přístup do administrace z tohoto webu', 'Block access to the administration of this site', '', '', NULL, NULL),
(530, 0, NULL, 'word527', 'Vyžadovat přístup přes https', 'Require access via https', '', '', NULL, NULL),
(531, 0, NULL, 'word528', 'IP restrikce', 'IP restrictions', '', '', NULL, NULL),
(532, 0, NULL, 'word529', 'Povolit všem', 'Allow all', '', '', NULL, NULL),
(533, 0, NULL, 'word530', 'Povolit přístup následujícím IP adresám', 'Allow access to the following IPs', '', '', NULL, NULL),
(534, 0, NULL, 'word531', 'Zakázat přístup následujícím IP adresám', 'Disable access to the following IPs', '', '', NULL, NULL),
(535, 0, NULL, 'word532', 'Zde zapište IP adresy oddělené čárkou', 'Here enter the IP addresses, separated by commas', '', '', NULL, NULL),
(536, 0, NULL, 'word533', 'Ip restrikce do administrace', 'Ip restrictions to administration', '', '', NULL, NULL),
(537, 0, NULL, 'word534', 'Css', 'Css', '', '', NULL, NULL),
(538, 0, NULL, 'word535', 'Načítat odkazy přes ajax', 'Read links via ajax', '', '', NULL, NULL),
(539, 0, NULL, 'word536', 'Historie', 'Hystory', '', '', NULL, NULL),
(540, 0, NULL, 'word537', 'Datum vytvoření verze', 'Creation date versions', '', '', NULL, NULL),
(541, 0, NULL, 'word538', 'Otevřít verzi', 'Open version', '', '', NULL, NULL),
(542, 0, NULL, 'word539', 'Položky k publikaci', 'Items for publication', '', '', NULL, NULL),
(543, 0, NULL, 'word540', 'Publikovat', 'Publish', '', '', NULL, NULL),
(544, 0, NULL, 'word541', 'Editovat', 'Edit', '', '', NULL, NULL),
(545, 0, NULL, 'word542', 'Zobrazit na webu', 'View on the web', '', '', NULL, NULL),
(546, 0, NULL, 'word543', 'Ankety', 'Survey', '', '', NULL, NULL),
(547, 0, NULL, 'word544', 'Mailing', 'Mailing', '', '', NULL, NULL),
(548, 0, NULL, 'word545', 'Nový mailing', 'New mailing', '', '', NULL, NULL),
(549, 0, NULL, 'word546', 'Editovat mailing', 'Edit mailing', '', '', NULL, NULL),
(550, 0, NULL, 'word547', 'Odstranit mailing', 'Delete mailing', '', '', NULL, NULL),
(551, 0, NULL, 'word548', 'Email', 'E-mail', '', '', NULL, NULL),
(552, 0, NULL, 'word549', 'Vyberte', 'Select', '', '', NULL, NULL),
(553, 0, NULL, 'word550', 'Mailingová skupina', 'Mailing groups', '', '', NULL, NULL),
(554, 0, NULL, 'word551', 'Kontakty', 'Contacts', '', '', NULL, NULL),
(555, 0, NULL, 'word552', 'Přidat kontakt', 'Add contact', '', '', NULL, NULL),
(556, 0, NULL, 'word553', 'Přidat kontakt', 'Add contact', '', '', NULL, NULL),
(557, 0, NULL, 'word554', 'E-mail', 'E-mail', '', '', NULL, NULL),
(558, 0, NULL, 'word555', 'Uložit kontakt', 'Add contacts', '', '', NULL, NULL),
(559, 0, NULL, 'word556', 'Upravit', 'Edit', '', '', NULL, NULL),
(560, 0, NULL, 'word557', 'Smazat', 'Delete', '', '', NULL, NULL),
(561, 0, NULL, 'word558', 'Mailingové skupiny', 'Mailing groups', '', '', NULL, NULL),
(562, 0, NULL, 'word559', 'Odeslat mailing', 'Send mailing', '', '', NULL, NULL),
(563, 0, NULL, 'word560', 'Odesílatel emailu', 'The sender email', '', '', NULL, NULL),
(564, 0, NULL, 'word561', 'Zdroje dat', 'Data sources', '', '', NULL, NULL),
(565, 0, NULL, 'word562', 'Nový zdroj dat', 'New data source', '', '', NULL, NULL),
(566, 0, NULL, 'word563', 'Editovat', 'Edit', '', '', NULL, NULL),
(567, 0, NULL, 'word564', 'Odstranit', 'Delete', '', '', NULL, NULL),
(568, 0, NULL, 'word565', 'Zdroje dat', 'Data sources', '', '', NULL, NULL),
(569, 0, NULL, 'word566', 'Editace zdroje', 'Editing resources', '', '', NULL, NULL),
(570, 0, NULL, 'word567', 'Typ zdroje dat', 'Type of data source', '', '', NULL, NULL),
(571, 0, NULL, 'word568', 'Vyberte', 'Select', '', '', NULL, NULL),
(572, 0, NULL, 'word569', 'Importní xml', 'Import xml', '', '', NULL, NULL),
(573, 0, NULL, 'word570', 'Exportní xml', 'Export xml', '', '', NULL, NULL),
(574, 0, NULL, 'word571', 'Začátek xml souboru', 'Beginning xml file', '', '', NULL, NULL),
(575, 0, NULL, 'word572', 'Konec xml souboru', 'End xml file', '', '', NULL, NULL),
(576, 0, NULL, 'word573', 'Xml item', 'Xml item', '', '', NULL, NULL),
(577, 0, NULL, 'word574', 'Začátek xml itemu', 'Beginning xml item', '', '', NULL, NULL),
(578, 0, NULL, 'word575', 'Konec xml itemu', 'End xml item', '', '', NULL, NULL),
(579, 0, NULL, 'word576', 'Importní url adresa', 'Import url', '', '', NULL, NULL),
(580, 0, NULL, 'word577', 'Podmínka pro vyhledávání v XML', 'The condition for searching XML', '', '', NULL, NULL),
(581, 0, NULL, 'word578', 'Způsob importu', 'How to import', '', '', NULL, NULL),
(582, 0, NULL, 'word579', 'Smazat vše a přidat znovu', 'Delete all and add again', '', '', NULL, NULL),
(583, 0, NULL, 'word580', 'Pouze přidat nové záznamy', 'Only to add new records', '', '', NULL, NULL),
(584, 0, NULL, 'word581', 'Pouze aktualizovat existující záznamy', 'Only update existing records', '', '', NULL, NULL),
(585, 0, NULL, 'word582', 'Přidat nové záznamy a aktualizovat stávající', 'Add new records and update existing', '', '', NULL, NULL),
(586, 0, NULL, 'word583', 'Testovat existenci záznamu podle sloupce', 'Test the existence of an alert by column', '', '', NULL, NULL);
INSERT INTO `WordGroups` (`Id`, `Deleted`, `IsSystem`, `GroupName`, `WordCS`, `WordEN`, `WordSK`, `WordDE`, `WordRU`, `WordRU,8`) VALUES
(587, 0, NULL, 'word584', 'Exportní xml z uživatelské položky', 'XML export of user entries', '', '', NULL, NULL),
(588, 0, NULL, 'word585', 'Uživatelský objekt', 'Custom object', '', '', NULL, NULL),
(589, 0, NULL, 'word586', 'Zvolit objekt', 'Select object', '', '', NULL, NULL),
(590, 0, NULL, 'word587', '!UPOZONĚNÍ!', '!NOTICE!', '', '', NULL, NULL),
(591, 0, NULL, 'word588', 'Exportují se podřízené položky a je nutné aby měli stejný uživatelský číselník (šablonu).', 'Export to child items, and it is necessary to have the same userdial (template).', '', '', NULL, NULL),
(592, 0, NULL, 'word589', 'Importní xml do uživatelské položky', 'Import xml to the user entries', '', '', NULL, NULL),
(593, 0, NULL, 'word590', 'ID objektu', 'Object ID', '', '', NULL, NULL),
(594, 0, NULL, 'word591', 'Seo url objektu', 'Seo url object', '', '', NULL, NULL),
(595, 0, NULL, 'word592', 'Jméno objektu', 'Object name', '', '', NULL, NULL),
(596, 0, NULL, 'word593', 'Identifikátor objektu', 'The object identifier', '', '', NULL, NULL),
(597, 0, NULL, 'word594', 'Položky v číselníku', 'Items in the dial', '', '', NULL, NULL),
(598, 0, NULL, 'word595', 'Prohlížeč logů', 'Log viewer', '', '', NULL, NULL),
(599, 0, NULL, 'word596', 'Přiřazená šablona pro podřízené objekty', 'Assigned template for the child objects', '', '', NULL, NULL),
(600, 0, NULL, 'word597', 'Při vytváření objektu načíst data z parenta', 'When creating an object to retrieve data from a parent', '', '', NULL, NULL),
(601, 0, NULL, 'word598', 'Provést import', 'To import', '', '', NULL, NULL),
(602, 0, NULL, 'word599', 'Vyexportovat xml', 'XML export', '', '', NULL, NULL),
(603, 0, NULL, 'word600', 'V xml exportu obalit do CDATA', 'In XML Export wrapped in CDATA', '', '', NULL, NULL),
(604, 0, NULL, 'word601', 'Vygenerovat xml item', 'Generate xml item', '', '', NULL, NULL),
(605, 0, NULL, 'word602', 'Zobrazit pouze v detailu', 'Only show in detail', '', '', NULL, NULL),
(606, 0, NULL, 'word603', 'Po přihlášení přejít na', 'After login', '', '', NULL, NULL),
(607, 0, NULL, 'word604', 'Vyberte', 'Select', '', '', NULL, NULL),
(608, 0, NULL, 'word605', 'Položku se nepodařilo smazat. Pravděpodobně nemáte dostatečná oprávnění.', 'Failed to delete the item. You may not have sufficient privileges.', '', '', NULL, NULL),
(609, 0, NULL, 'word606', 'Přesunutí položky se nezdařilo. Pravděpodobně nemáte dostatečná oprávnění!', 'Move an item failed. You may not have sufficient privileges!', '', '', NULL, NULL),
(610, 0, NULL, 'word607', 'Kopírování položky se nezdařilo. Pravděpodobně nemáte dostatečná oprávnění!', 'Copying entries failed. You may not have sufficient privileges!', '', '', NULL, NULL),
(611, 0, NULL, 'word608', 'Začátek subitemu', 'Beginning subito', '', '', NULL, NULL),
(612, 0, NULL, 'word609', 'XML subitem', 'XML subito', '', '', NULL, NULL),
(613, 0, NULL, 'word610', 'XML subitem konec', 'XML subito end', '', '', NULL, NULL),
(614, 0, NULL, 'word611', 'XML subitem item začátek', 'XML subito item start', '', '', NULL, NULL),
(615, 0, NULL, 'word612', 'XML subitem item konec', 'XML subito end item', '', '', NULL, NULL),
(616, 0, NULL, 'word613', 'Ankety', 'Survey', '', '', NULL, NULL),
(617, 0, NULL, 'word614', 'Nová anketa', 'New survey', '', '', NULL, NULL),
(618, 0, NULL, 'word615', 'Detail ankety', 'Detail survey', '', '', NULL, NULL),
(619, 0, NULL, 'word616', 'Anketní otázka', 'Poll question', '', '', NULL, NULL),
(620, 0, NULL, 'word617', 'Odpověď', 'Answer', '', '', NULL, NULL),
(621, 0, NULL, 'word618', 'Povolit možnost jiné', 'Allow other option', '', '', NULL, NULL),
(622, 0, NULL, 'word619', 'Povolit výběr z více možností', 'Allow multiple choice', '', '', NULL, NULL),
(623, 0, NULL, 'word620', 'Mód formuláře', 'Mode form', '', '', NULL, NULL),
(624, 0, NULL, 'word621', 'Vše na jednu stránku', 'All on one page', '', '', NULL, NULL),
(625, 0, NULL, 'word622', 'Průvodce', 'Guide', '', '', NULL, NULL),
(626, 0, NULL, 'word623', 'Text tlačítka další', 'Text button next', '', '', NULL, NULL),
(627, 0, NULL, 'word624', 'Text tlačítka zpět', 'Text back button', '', '', NULL, NULL),
(628, 0, NULL, 'word625', 'Možnosti validace', 'Options validation', '', '', NULL, NULL),
(629, 0, NULL, 'word626', 'Validovat každý krok formuláře zvlášť', 'Validate each step separately form', '', '', NULL, NULL),
(630, 0, NULL, 'word627', 'Validovat až na konci', 'Validate at the end', '', '', NULL, NULL),
(631, 0, NULL, 'word628', 'Skupiny položek', 'Groups', '', '', NULL, NULL),
(632, 0, NULL, 'word629', 'Jméno skupiny', 'Group name', '', '', NULL, NULL),
(633, 0, NULL, 'word630', 'Položky ve skupině', 'Items in group', '', '', NULL, NULL),
(634, 0, NULL, 'word631', 'Mód číselníku', 'Mode dial', '', '', NULL, NULL),
(635, 0, NULL, 'word632', 'Standardní', 'Standard', '', '', NULL, NULL),
(636, 0, NULL, 'word633', '1 z N', '1 of N', '', '', NULL, NULL),
(637, 0, NULL, 'word634', 'M z N', 'M of N', '', '', NULL, NULL),
(638, 0, NULL, 'word635', 'Formát zobrazovaného názvu při použití v subčíselníku (varianty 1 z N a M z N)', 'The format of the display name when you use the sub dial (option 1 of N and M of N)', '', '', NULL, NULL),
(639, 0, NULL, 'word636', 'Před dokončením zobrazit souhrn', 'Before finalizing show summary', '', '', NULL, NULL),
(640, 0, NULL, 'word637', 'Nadpis posledního kroku průvodce', 'Heading the last step guide', '', '', NULL, NULL),
(641, 0, NULL, 'word638', 'Javascriptový framework', 'JavaScript framework', '', '', NULL, NULL),
(642, 0, NULL, 'word639', 'Bez frameworku', 'Without framework', '', '', NULL, NULL),
(643, 0, NULL, 'word640', 'Použít jquery', 'Use jquery', '', '', NULL, NULL),
(644, 0, NULL, 'word641', 'Vyčištění databáze', 'Database cleanup', '', '', NULL, NULL),
(645, 0, NULL, 'word642', 'Vymazat smazané položky obsahu', 'Erase deleted items content', '', '', NULL, NULL),
(646, 0, NULL, 'word643', 'Vymazat položky, které nemají parenta', 'Delete items that do not have a parent', '', '', NULL, NULL),
(647, 0, NULL, 'word644', 'Vymazat poškozené položky', 'Delete the damaged item', '', '', NULL, NULL),
(648, 0, NULL, 'word645', 'Vymazat smazané uživatelské účty', 'Erase deleted user accounts', '', '', NULL, NULL),
(649, 0, NULL, 'word646', 'Vymazat smazané uživatelské skupiny', 'Erase deleted user groups', '', '', NULL, NULL),
(650, 0, NULL, 'word647', 'Vymazat smazané weby', 'Erase deleted sites', '', '', NULL, NULL),
(651, 0, NULL, 'word648', 'Smazat smazané jazykové verze webu', 'Delete delete language version of the site', '', '', NULL, NULL),
(652, 0, NULL, 'word649', 'Smazat smazané jazyky administrace', 'Delete delete languages administration', '', '', NULL, NULL),
(653, 0, NULL, 'word650', 'Smazat smazaná slova', 'Delete delete the words', '', '', NULL, NULL),
(654, 0, NULL, 'word651', 'Smazat smazané moduly', 'Delete delete Modules', '', '', NULL, NULL),
(655, 0, NULL, 'word652', 'Smazat smazané číselníky', 'Delete delete dials', '', '', NULL, NULL),
(656, 0, NULL, 'word653', 'Provést', 'Perform', '', '', NULL, NULL),
(657, 0, NULL, 'word654', 'Možnosti filtrování', 'Filtering options', '', '', NULL, NULL),
(658, 0, NULL, 'word655', 'Nezobrazovat ve filtru', 'Hide in the filter', '', '', NULL, NULL),
(659, 0, NULL, 'word656', 'Rozsah', 'Range', '', '', NULL, NULL),
(660, 0, NULL, 'word657', 'Vyhledávací pole - obsahuje přesně', 'A search box - contains exactly', '', '', NULL, NULL),
(661, 0, NULL, 'word658', 'Začíná', 'Begins', '', '', NULL, NULL),
(662, 0, NULL, 'word659', 'Končí', 'Ends', '', '', NULL, NULL),
(663, 0, NULL, 'word660', 'Obsahuje', 'Contains', '', '', NULL, NULL),
(664, 0, NULL, 'word661', 'Výběr M z N', 'Selection of M N', '', '', NULL, NULL),
(665, 0, NULL, 'word662', 'Menší než', 'Smaller than', '', '', NULL, NULL),
(666, 0, NULL, 'word663', 'Menší nebo rovno', 'Less than or equal', '', '', NULL, NULL),
(667, 0, NULL, 'word664', 'Větší nebo rovno', 'Greater or equal', '', '', NULL, NULL),
(668, 0, NULL, 'word665', 'Větší než', 'Bigger than', '', '', NULL, NULL),
(669, 0, NULL, 'word666', 'Výběr 1 z N', 'Choosing 1 from N', '', '', NULL, NULL),
(670, 0, NULL, 'word667', 'Vygenerovat pdf do přílohy emailu', 'Generate PDF attachments to e-mail', '', '', NULL, NULL),
(671, 0, NULL, 'word668', 'Šablona PDF', 'Template PDF', '', '', NULL, NULL),
(672, 0, NULL, 'word669', 'Vyberte', 'Select', '', '', NULL, NULL),
(673, 0, NULL, 'word670', 'Jméno přiloženého souboru(bez přípony)', 'The name of the attached file (without extension)', '', '', NULL, NULL),
(674, 0, NULL, 'word671', 'Aktivovat autocomplete', 'Activate autocomplete', '', '', NULL, NULL),
(675, 0, NULL, 'word672', 'Přidat do řazení', 'Add to sort', '', '', NULL, NULL),
(676, 0, NULL, 'word673', 'Aktivovat stránkování', 'Activate pagination', '', '', NULL, NULL),
(677, 0, NULL, 'word674', 'Při prvním načtení načíst', 'When you first load to load', '', '', NULL, NULL),
(678, 0, NULL, 'word675', 'V dalším kroku načíst', 'In the next step to load', '', '', NULL, NULL),
(679, 0, NULL, 'word676', 'Načíst další', 'Load more', '', '', NULL, NULL),
(680, 0, NULL, 'word677', 'Javascriptová událost', 'JavaScript event', '', '', NULL, NULL),
(681, 0, NULL, 'word678', 'Zavolat javasciptovou funkci', 'Call the JavaScript function', '', '', NULL, NULL),
(682, 0, NULL, 'word679', 'Alternativní obsah', 'Alternative content', '', '', NULL, NULL),
(683, 0, NULL, 'word680', 'Uživatelská skupina', 'User group', '', '', NULL, NULL),
(684, 0, NULL, 'word681', 'Alternativní článek', 'Alternative article', '', '', NULL, NULL),
(685, 0, NULL, 'word682', 'Přidat článek', 'Add article', '', '', NULL, NULL),
(686, 0, NULL, 'word683', 'Alternativní položka', 'Alternative entry', '', '', NULL, NULL),
(687, 0, NULL, 'word684', 'Připojená anketa', 'Attached poll', '', '', NULL, NULL),
(688, 0, NULL, 'word685', 'Text možnosti \"jiné\"', 'The text of the \"other\"', '', '', NULL, NULL),
(689, 0, NULL, 'word686', 'Text tlačítka odeslat', 'Text button to submit', '', '', NULL, NULL),
(690, 0, NULL, 'word687', 'Statistika odpovědí', 'Statistics responses', '', '', NULL, NULL),
(691, 0, NULL, 'word688', 'Vedlejší uživatelské skupiny', 'Minor user group', '', '', NULL, NULL),
(692, 0, NULL, 'word689', 'Zkontrolovat soubor', 'Check file', '', '', NULL, NULL),
(693, 0, NULL, 'word690', 'Přidat inzerát', 'Add item', '', '', NULL, NULL),
(694, 0, NULL, 'word691', 'Nový inzerát', 'New item', '', '', NULL, NULL),
(695, 0, NULL, 'word692', 'Uložit', 'Save', '', '', NULL, NULL),
(696, 0, NULL, 'word693', 'Cancel', 'Cancel', '', '', NULL, NULL),
(697, 0, NULL, 'word694', 'Uložit do ...', '', '', '', NULL, NULL),
(698, 0, NULL, 'word695', 'Uložit do', 'Save to', '', '', NULL, NULL),
(699, 0, NULL, 'word696', 'Vybrat', 'Select', '', '', NULL, NULL),
(700, 0, NULL, 'word697', 'Speciální pole formuáře', '', '', '', NULL, NULL),
(701, 0, NULL, 'word698', 'Jméno objektu', 'Object name', '', '', NULL, NULL),
(702, 0, NULL, 'word699', 'Na frontendu nenačítat podobjekty', 'Disable Load subobjects (frontend)', '', '', NULL, NULL),
(703, 0, NULL, 'word700', 'Opravdu si přejete odstranit zvolenou položku?', 'Do you really want to delete the selected item?', '', '', NULL, NULL),
(704, 0, NULL, 'word701', 'Zobrazit', 'Show', '', '', NULL, NULL),
(705, 0, NULL, 'word702', 'Cancel', 'Cancel', '', '', NULL, NULL),
(706, 0, NULL, 'word703', 'Editace položky', 'Item edit', '', '', NULL, NULL),
(707, 0, NULL, 'word704', 'Uložit', 'Save', '', '', NULL, NULL),
(708, 0, NULL, 'word705', 'Závislosti', 'Addictions', '', '', NULL, NULL),
(709, 0, NULL, 'word706', 'Jméno závislosti', 'Addictions name', '', '', NULL, NULL),
(710, 0, NULL, 'word707', 'Detail závislosti', 'Detail addiction', '', '', NULL, NULL),
(711, 0, NULL, 'word708', 'Obecné nastavení', 'General settings', '', '', NULL, NULL),
(712, 0, NULL, 'word709', 'Jméno závislosti', 'Addictions name', '', '', NULL, NULL),
(713, 0, NULL, 'word710', 'Položka 1', 'Item 1', '', '', NULL, NULL),
(714, 0, NULL, 'word711', 'Pravidlo', 'Rule', '', '', NULL, NULL),
(715, 0, NULL, 'word712', 'Hodnota 1', 'Value 1', '', '', NULL, NULL),
(716, 0, NULL, 'word713', 'Akce', 'Action', '', '', NULL, NULL),
(717, 0, NULL, 'word714', 'Zobrazit', 'Show', '', '', NULL, NULL),
(718, 0, NULL, 'word715', 'Skrýt', 'Hide', '', '', NULL, NULL),
(719, 0, NULL, 'word716', 'Nastavit hodnotu', 'Set value', '', '', NULL, NULL),
(720, 0, NULL, 'word717', 'Hodnota', 'Value', '', '', NULL, NULL),
(721, 0, NULL, 'word718', 'Ovlivněné pole', 'Affected field', '', '', NULL, NULL),
(722, 0, NULL, 'word719', 'Priorita', 'Priority', '', '', NULL, NULL),
(723, 0, NULL, 'word720', 'Zaškrtnuto', 'Checked', '', '', NULL, NULL),
(724, 0, NULL, 'word721', 'Automatické doplňování slov', 'Autocompletion words', '', '', NULL, NULL),
(725, 0, NULL, 'word722', 'Hodnota', 'Value', '', '', NULL, NULL),
(726, 0, NULL, 'word723', 'Oprávnění na odkaz', 'Permission to link', '', '', NULL, NULL),
(727, 0, NULL, 'word724', 'Nastavení ankety', 'Setting polls', '', '', NULL, NULL),
(728, 0, NULL, 'word725', 'Nastavení zdroje dat', 'Setting data sources', '', '', NULL, NULL),
(729, 0, NULL, 'word726', 'Položky v číselníku', 'Items in the dial', '', '', NULL, NULL),
(730, 0, NULL, 'word727', 'Přidání hodnoty', 'Adding value', '', '', NULL, NULL),
(731, 0, NULL, 'word728', 'Profil uživatele', 'User profile', '', '', NULL, NULL),
(732, 0, NULL, 'word729', 'Složka', 'Folder', '', '', NULL, NULL),
(733, 0, NULL, 'word730', 'Članek', 'Article', '', '', NULL, NULL),
(734, 0, NULL, 'word731', 'FileUpload', 'FileUpload', '', '', NULL, NULL),
(735, 0, NULL, 'word732', 'Nevhodná slova', 'Bad words', '', '', NULL, NULL),
(736, 0, NULL, 'word733', 'Novinky', 'News', '', '', NULL, NULL),
(737, 0, NULL, 'word734', 'Logo', 'Logo', '', '', NULL, NULL),
(738, 0, NULL, 'word735', 'Ulice', 'Street', '', '', NULL, NULL),
(739, 0, NULL, 'word736', 'Jméno skupiny', 'Group name', '', '', NULL, NULL),
(740, 0, NULL, 'word737', 'Registrovaný uživatel', 'Registered user', '', '', NULL, NULL),
(741, 0, NULL, 'word738', 'Jméno objektu', 'Object name', '', '', NULL, NULL),
(742, 0, NULL, 'word739', 'SeoUrl', 'SeoUrl', '', '', NULL, NULL),
(743, 0, NULL, 'word740', 'Akce prováděná pro přihlášení uživatele', '', '', '', NULL, NULL),
(744, 0, NULL, 'word741', 'Přejít na homepage', '', '', '', NULL, NULL),
(745, 0, NULL, 'word742', 'Zůstat na aktuální stránce', '', '', '', NULL, NULL),
(746, 0, NULL, 'word743', 'Přejít na URL', '', '', '', NULL, NULL),
(747, 0, NULL, 'word744', 'Přejít na url', '', '', '', NULL, NULL),
(748, 0, NULL, 'word745', 'Uživatelské jméno:', 'Username:', '', '', NULL, NULL),
(749, 0, NULL, 'word746', 'Heslo:', '', '', '', NULL, NULL),
(750, 0, NULL, 'word747', 'Přihlásit se', 'Login', '', '', NULL, NULL),
(751, 0, NULL, 'word748', 'Heslo znovu:', '', '', '', NULL, NULL),
(752, 0, NULL, 'word749', 'Jméno', '', '', '', NULL, NULL),
(753, 0, NULL, 'word750', 'Příjmení', '', '', '', NULL, NULL),
(754, 0, NULL, 'word751', 'Email', '', '', '', NULL, NULL),
(755, 0, NULL, 'word752', 'Zaregistrovat se', '', '', '', NULL, NULL),
(756, 0, NULL, 'word753', 'Poslat email administrátorovi', '', '', '', NULL, NULL),
(757, 0, NULL, 'word754', 'Email administátora kam příjde email o registraci uživatele', '', '', '', NULL, NULL),
(758, 0, NULL, 'word756', 'Text emailu pro administrátora', '', '', '', NULL, NULL),
(759, 0, NULL, 'word757', 'Posílat info email uživatelovi', '', '', '', NULL, NULL),
(760, 0, NULL, 'word758', 'Odesílatel emailu pro uživatele', '', '', '', NULL, NULL),
(761, 0, NULL, 'word759', 'Email pro uživatele', '', '', '', NULL, NULL),
(762, 0, NULL, 'word760', 'Vyžadovat cookies souhlas', '', '', '', NULL, NULL),
(763, 0, NULL, 'word761', 'Upozorňujeme, že tyto stránky používají cookies. Tím, že na stránkách setrváte, souhlasíte s jejich používáním.', '', '', '', '', NULL),
(764, 0, NULL, 'word762', 'Více informací', '', '', '', NULL, NULL),
(765, 0, NULL, 'word763', 'Souhlasím', '', '', '', NULL, NULL),
(766, 0, NULL, 'word764', 'Data šablony', '', '', '', NULL, NULL),
(767, 0, NULL, 'word765', 'Nová diskuze', '', '', '', NULL, NULL),
(768, 0, NULL, 'word766', 'Nevybrali jste uživatelskou skupinu nebo objekt!', '', '', '', NULL, NULL),
(769, 0, NULL, 'word767', 'Vyčistit log', '', '', '', NULL, NULL),
(770, 0, NULL, 'word768', 'Stáhnout log', '', '', '', NULL, NULL),
(771, 0, NULL, 'word769', 'Instalace systému', '', '', '', NULL, NULL),
(772, 0, NULL, 'word770', 'Profil uživatele', '', '', '', NULL, NULL),
(773, 0, NULL, 'word771', 'Uložit, publikovat a zpět', '', '', '', NULL, NULL),
(774, 0, NULL, 'word772', 'Uložit a zpět', '', '', '', NULL, NULL),
(775, 0, NULL, 'word773', 'Nahrát více souborů', '', '', '', NULL, NULL),
(776, 0, NULL, 'word774', 'Datum posledního importu', '', '', '', NULL, NULL),
(777, 0, NULL, 'word775', 'Skrýté záložky', '', '', '', NULL, NULL),
(778, 0, NULL, 'word776', 'Skrýt souvisejicí položky', '', '', '', NULL, NULL),
(779, 0, NULL, 'word777', 'Skrýt galerii', '', '', '', NULL, NULL),
(780, 0, NULL, 'word778', 'Skrýt ostatní objekty', '', '', '', NULL, NULL),
(781, 0, NULL, 'word779', 'Skrýt alternativní obsah', '', '', '', NULL, NULL),
(782, 0, NULL, 'word780', 'Podle jména', '', '', '', NULL, NULL),
(783, 0, NULL, 'word781', 'vzestupně', '', '', '', NULL, NULL),
(784, 0, NULL, 'word782', 'sestupně', '', '', '', NULL, NULL),
(785, 0, NULL, 'word783', 'Přejít do diskuze', '', '', '', NULL, NULL),
(786, 0, NULL, 'word784', 'CSS detail', '', '', '', NULL, NULL),
(787, 0, NULL, 'tatiana1', 'S', 'S', '', '', 'S', NULL),
(788, 0, NULL, 'tatiana2', 'M', 'M', '', '', 'M', NULL),
(789, 0, NULL, 'tatiana3', 'L', 'L', '', '', 'L', NULL),
(790, 0, NULL, 'tatiana4', 'XL', 'XL', '', '', 'XL', NULL),
(791, 0, NULL, 'tatiana5', 'XXL', 'XXL', '', '', 'XXL', NULL),
(792, 0, NULL, 'tatiana6', 'XXXL', 'XXXL', '', '', 'XXXL', NULL),
(793, 0, NULL, 'word785', 'Vložit do košíku', 'Add to shopping basket', '', '', 'Добавить в корзину', NULL),
(794, 0, NULL, 'tatiana7', 'Vyberte velikost', 'Select size', '', '', 'Выбрать размер', NULL),
(795, 0, NULL, 'word786', 'Jméno produktu', 'Product name', '', '', 'Название товара', NULL),
(796, 0, NULL, 'word787', 'Cena za kus', 'Price for 1 piece excl. VAT', '', '', 'Цена за шт.', NULL),
(797, 0, NULL, 'word788', 'Cena za kus s DPH', 'Price for 1 piece incl. VAT', '', '', 'Цена за шт. с НДС', NULL),
(798, 0, NULL, 'word789', 'Počet kusů', 'Number', '', '', 'Количество', NULL),
(799, 0, NULL, 'word790', 'Cena celkem', 'Total excl. VAT', '', '', 'Всего', NULL),
(800, 0, NULL, 'word791', 'Cena celkem s DPH', 'Total incl. VAT', '', '', 'Всего с НДС', NULL),
(801, 0, NULL, 'word792', 'Váš košík je prázdný', 'Your shopping basket is empty', '', '', 'В корзине нет товаров', NULL),
(802, 0, NULL, 'word793', 'Celkem', 'Total excl. VAT', '', '', 'Итого', NULL),
(803, 0, NULL, 'word794', 'Celkem s DPH', 'Total incl. VAT', '', '', 'Итого с НДС', NULL),
(804, 0, NULL, 'word795', 'Počet kusů', 'Quantity', '', '', 'количество шт.', NULL),
(805, 0, NULL, 'word796', 'Událost při změně', '', '', '', NULL, NULL),
(806, 0, NULL, 'word797', 'Funkce volané při odeslání formuláře', '', '', '', NULL, NULL),
(807, 0, NULL, 'word798', 'Položek v košíku', '', '', '', NULL, NULL),
(808, 0, NULL, 'word799', 'Přejít do košíku', '', '', '', NULL, NULL),
(809, 0, NULL, 'word800', 'Začít nakupovat', '', '', '', NULL, NULL),
(810, 0, NULL, 'word801', '5 a více kusů skladem', '5 and more piece are avaiable', '', '', '5 и больше шт. в наличии', NULL),
(811, 0, NULL, 'word802', '2 - 4 kusy skladem', '2-4 pieces are avaiable', '', '', '2-4 шт. в наличии', NULL),
(812, 0, NULL, 'word803', 'Poslední kus skladem', '1 piece is available', '', '', '1 шт. в наличии', NULL),
(813, 0, NULL, 'word804', 'Zboží není dostupné', 'This good is unavailable', '', '', 'Товар не доступен', NULL),
(814, 0, NULL, 'word805', 'Zboží je na cestě', 'The good is on the way', '', '', 'Товар в пути', NULL),
(815, 0, NULL, 'word806', 'Zboiží je skladem u výrobce', "The good is available at the producer's"  , '', '', 'Товар в наличии у произвдителя', NULL),
(816, 0, NULL, 'word807', 'Předobjednávky', 'Pre-ordr', '', '', 'Предзаказ', NULL),
(817, 0, NULL, 'word808', 'Dostupné na dotaz', 'Available on the request', '', '', 'Доступность по запросу', NULL),
(818, 0, NULL, 'word809', 'Dostupné do 14-ti dnů', 'Available up tu 14 days', '', '', 'Доступность в течении 14 дней', NULL),
(819, 0, NULL, 'word810', 'Zaškrtávací pole', '', '', '', NULL, NULL),
(820, 0, NULL, 'tatiana8', 'XXS', 'XXS', '', '', 'XXS', NULL),
(821, 0, NULL, 'tatiana9', 'XS', 'XS', '', '', 'XS', NULL),
(822, 0, NULL, 'tatiana10', '4XL', '4XL', '', '', '4XL', NULL),
(823, 0, NULL, 'tatiana11', 'Univerzální', '', '', '', NULL, NULL),
(824, 0, NULL, 'word811', 'Cena', '', '', '', 'Цена', NULL),
(825, 0, NULL, 'tatiana12', 'Novinky ', 'New', '', '', 'Новинки', NULL),
(826, 0, NULL, 'tatiana13', '36', '36', '', '', '36', NULL),
(827, 0, NULL, 'tatiana14', '37', '37', '', '', '37', NULL),
(828, 0, NULL, 'tatiana15', '38', '38', '', '', '38', NULL),
(829, 0, NULL, 'tatiana16', '39', '39', '', '', '39', NULL),
(830, 0, NULL, 'tatiana17', '40', '40', '', '', '40', NULL),
(831, 0, NULL, 'tatiana18', '41', '41', '', '', '41', NULL),
(832, 0, NULL, 'tatiana19', '42', '42', '', '', '42', NULL),
(833, 0, NULL, 'tatiana20', '43', '43', '', '', '43', NULL),
(834, 0, NULL, 'tatiana21', '44', '44', '', '', '44', NULL),
(835, 0, NULL, 'tatiana22', '45', '45', '', '', '45', NULL),
(836, 0, 0, 'word812', 'Barva', 'Color', NULL, NULL, 'Цвет', NULL),
(837, 0, 0, 'word813', 'Dostupnost produktu', 'Availability', NULL, NULL, 'Доступность товара', NULL),
(838, 0, 0, 'word814', 'Složení', 'Composition', NULL, NULL, 'Состав', NULL),
(839, 0, 0, 'word815', 'Velikost', 'Size', NULL, NULL, 'Размер', NULL),
(840, 0, 0, 'word816', 'Informace o produktu', 'Product info', NULL, NULL, 'Информация о товаре', NULL),
(841, 0, 0, 'word817', 'Varianty', 'Options', NULL, NULL, 'Варианты', NULL),
(842, 0, 0, 'word818', 'Dotaz k produktu', 'FAQ', NULL, NULL, 'Вопрос о товаре', NULL),
(843, 0, 0, 'word819', 'Gallerie', 'Gallery', NULL, NULL, 'Галерея', NULL),
(844, 0, 0, 'word820', 'Souvisejicí produkty', 'Related products', NULL, NULL, 'Похожие товары', NULL),
(845, 0, 0, 'word821', 'Košík', 'Shopping basket', NULL, NULL, 'Корзина', NULL),
(846, 0, 0, 'word822', 'Dodací údaje', 'Delivery', NULL, NULL, 'Условия доставки', NULL),
(847, 0, 0, 'word823', 'Doprava a platba', 'Delivery and payment', NULL, NULL, 'Доставка и оплата', NULL),
(848, 0, 0, 'word824', 'Sourhn', 'Total', NULL, NULL, 'Итого', NULL),
(849, 0, 0, 'word825', 'Pokračovat v nákupu', 'Continue', NULL, NULL, 'Продолжить покупку', NULL),
(850, 0, 0, 'word826', 'Přejít k dodacím údajům', 'Go to the delivery condition', NULL, NULL, 'Перейти к условиям доставки', NULL),
(851, 0, 0, 'word827', 'Fakturační údaje', 'Payment info', NULL, NULL, 'Информация об оплате', NULL),
(852, 0, 0, 'word828', 'Dodací údaje', 'Terms of delivery', NULL, NULL, 'Параметры доставки', NULL),
(853, 0, 0, 'word829', 'Souhlasím s obchodními podmínkami', 'I agree with terms and conditions', NULL, NULL, 'Я соглашаюсь с правилами и условиями покупки и возврата товара', NULL),
(854, 0, 0, 'word830', 'Souhlasím se zasíláním obchodních nabídek', 'Subscibe Newsletters', NULL, NULL, 'Я соглашаюсь на рассылку от магазина ', NULL),
(855, 0, 0, 'word831', 'Zpět', 'Back', NULL, NULL, 'Назад', NULL),
(856, 0, 0, 'word832', 'Přejít k dopravě a platbě', 'Go to delivery and payment', NULL, NULL, 'Перейти к доставке и оплате', NULL),
(857, 0, 0, 'word833', 'Způsob dopravy', 'Way of delivery', NULL, NULL, 'Способ доставки', NULL),
(858, 0, 0, 'word834', 'Způsob platby', 'Ways to pay', NULL, NULL, 'Способ оплаты', NULL),
(859, 0, 0, 'word835', 'Zobrazit souhrn', 'Total cost', NULL, NULL, 'Показать итог', NULL),
(860, 0, 0, 'word836', 'Vaše objednávka', 'You order', NULL, NULL, 'Ваш заказ', NULL),
(861, 0, NULL, 'word837', 'Celková cena', 'Total excl. VAT', '', '', 'Всего', NULL),
(862, 0, 0, 'word838', 'Celková cena s DPH', 'Total incl. VAT', NULL, NULL, 'Всего с НДС', NULL),
(863, 0, 0, 'word839', 'Potvrzení objednávky', 'Confirmation of your order', NULL, NULL, 'Подтверждение заказа', NULL),
(864, 0, 0, 'word840', 'Jméno firmy', 'Company name', NULL, NULL, 'Название фирмы', NULL),
(865, 0, NULL, 'word841', 'IČ', 'SP', '', '', 'ИП', NULL),
(866, 0, NULL, 'word842', 'DIČ', 'ITN', '', '', 'ИНН', NULL),
(867, 0, 0, 'word843', 'Jméno a příjmení', 'Name and Surname', NULL, NULL, 'Имя и фамилия', NULL),
(868, 0, 0, 'word844', 'Město', 'City', NULL, NULL, 'Город', NULL),
(869, 0, 0, 'word845', 'Ulice', 'Steet', NULL, NULL, 'Улица', NULL),
(870, 0, 0, 'word846', 'PSČ', 'Zip code', NULL, NULL, 'Индекс', NULL),
(871, 0, 0, 'word847', 'Email', 'Email', NULL, NULL, 'Email', NULL),
(872, 0, 0, 'word848', 'Telefon', 'Phone', NULL, NULL, 'Телефон', NULL),
(873, 0, 0, 'word849', 'Variabilní symbol', 'Variable symbol', NULL, NULL, 'Вариабильный символ', NULL),
(874, 0, 0, 'word850', 'Dodavatel', 'Producer', NULL, NULL, 'Поставщик', NULL),
(875, 0, 0, 'word851', 'Jméno', 'Name', NULL, NULL, 'Имя', NULL),
(876, 0, 0, 'word852', 'Příjmení', 'Surname', NULL, NULL, 'Фамилия', NULL),
(877, 0, NULL, 'word853', 'Číslo popisné', 'Number', '', '', 'Номер', NULL),
(878, 0, NULL, 'word854', 'Povolit cachování  položky', '', '', '', '', NULL),
(879, 0, NULL, 'word855', 'Spráce cronů', '', '', '', '', NULL),
(880, 0, NULL, 'word856', 'Nastavení cronu', '', '', '', '', NULL),
(881, 0, NULL, 'word857', 'Jméno cronu', '', '', '', '', NULL),
(882, 0, NULL, 'word858', 'Cron url', '', '', '', '', NULL),
(883, 0, NULL, 'word859', 'Aktivní', '', '', '', '', NULL),
(884, 0, NULL, 'word860', 'Četnost spouštění', '', '', '', '', NULL),
(885, 0, NULL, 'word861', 'po 5 minutách', '', '', '', '', NULL),
(886, 0, NULL, 'word862', 'Titul  před', 'Title', '', '', '', NULL),
(887, 0, NULL, 'word863', 'Titul za', 'Title', '', '', '', NULL),
(888, 0, NULL, 'word864', '85D', '85D', '', '', '85D', NULL),
(889, 0, NULL, 'word865', '70A', '70A', '', '', '70A', NULL),
(890, 0, NULL, 'word866', '70B', '70B', '', '', '70B', NULL),
(891, 0, NULL, 'word867', '70C', '70C', '', '', '70C', NULL),
(892, 0, NULL, 'word868', '70D', '70D', '', '', '70D', NULL),
(893, 0, NULL, 'word869', '80A', '80A', '', '', '80A', NULL),
(894, 0, NULL, 'word870', '80B', '80B', '', '', '80B', NULL),
(895, 0, NULL, 'word871', '80C', '80C', '', '', '80C', NULL),
(896, 0, NULL, 'word872', '80D', '80D', '', '', '80D', NULL),
(897, 0, NULL, 'word873', '80E', '80E', '', '', '80E', NULL),
(898, 0, NULL, 'word874', '80F', '80F', '', '', '80F', NULL),
(899, 0, NULL, 'word875', '80G', '80G', '', '', '80G', NULL),
(900, 0, NULL, 'word876', '85A', '85A', '', '', '85A', NULL),
(901, 0, NULL, 'word877', '85B', '85B', '', '', '85B', NULL),
(902, 0, NULL, 'word878', '85C', '85C', '', '', '85C', NULL),
(903, 0, NULL, 'word879', '75A', '75A', '', '', '75A', NULL),
(904, 0, NULL, 'word880', '75B', '75B', '', '', '75B', NULL),
(905, 0, NULL, 'word881', '75C', '75C', '', '', '75C', NULL),
(906, 0, NULL, 'word882', '75D', '75D', '', '', '75D', NULL),
(907, 0, NULL, 'word883', '75E', '75E', '', '', '75E', NULL),
(908, 0, NULL, 'word884', '35', '35', '', '', '35', NULL),
(909, 0, NULL, 'word885', 'Nahrát obrázky', '', '', '', '', NULL),
(910, 0, NULL, 'word886', 'Smazat aktuální verzi', '', '', '', '', NULL),
(911, 0, NULL, 'word887', 'Opravdu si přejete smazat tuto jazykovou verzi objektu?', '', '', '', '', NULL),
(912, 0, NULL, 'word888', 'Exportní podmínka', '', '', NULL, '', NULL),
(913, 0, NULL, 'word889', 'Společná hodnota pro všechny jazykové verze', '', '', NULL, '', NULL),
(914, 0, NULL, 'word890', 'Způsob řazení', '', '', NULL, '', NULL),
(915, 0, NULL, 'word891', 'Výchozí řazení podle pozice', '', '', NULL, '', NULL),
(916, 0, NULL, 'word892', 'Podle jména', '', '', NULL, '', NULL),
(917, 0, NULL, 'word893', 'Od nejnovějších', '', '', NULL, '', NULL),
(918, 0, NULL, 'word894', 'Rootovský element', '', '', NULL, '', NULL),
(919, 0, NULL, 'word895', 'Pro ukládání dat použít skrytý input', '', '', NULL, '', NULL),
(920, 0, NULL, 'word896', 'Sloupec ukládaný do skrytého pole', '', '', NULL, '', NULL),
(921, 0, NULL, 'word897', 'Robots.txt', '', '', NULL, '', NULL),
(922, 0, NULL, 'word898', 'Sitemap.xml', '', '', NULL, '', NULL),
(923, 0, NULL, 'word899', 'Začátek sitemapy', '', '', NULL, '', NULL),
(924, 0, NULL, 'word900', 'Šablona odkazu', '', '', NULL, '', NULL),
(925, 0, NULL, 'word901', 'Šablona obrázku', '', '', NULL, '', NULL),
(926, 0, NULL, 'word902', 'Šablona videa', '', '', NULL, '', NULL),
(927, 0, NULL, 'word903', 'Konec sitemapy', '', '', NULL, '', NULL),
(928, 0, NULL, 'word904', 'Začátek itemu sitemapy', '', '', NULL, '', NULL),
(929, 0, NULL, 'word905', 'Konec item sitemapy', '', '', NULL, '', NULL),
(930, 0, NULL, 'word906', 'Šablona detailu statistiky formuláře', '', '', NULL, '', NULL),
(931, 0, NULL, 'word907', 'Stav objednávky', '', '', NULL, '', NULL);
